import type { FluxoCliente } from '@/types/wellness-system'

/**
 * Bloco 4 de Vendas no Pro Líderes:
 * continuidade dos clássicos Wellness em padrão novo de diagnóstico YLADA.
 */
export const proLideresSalesBlock4Fluxos: FluxoCliente[] = [
  {
    id: 'quiz-energetico',
    nome: 'Quiz Energético',
    objetivo: 'Avaliar padrão de energia e orientar próximo passo de forma simples.',
    perguntas: [
      { id: 'p1', texto: 'Você sente energia estável durante o dia?', tipo: 'sim_nao' },
      { id: 'p2', texto: 'Tem queda forte de disposição em algum horário?', tipo: 'sim_nao' },
      { id: 'p3', texto: 'Seu foco cai quando a rotina aperta?', tipo: 'sim_nao' },
      { id: 'p4', texto: 'Seu sono tem apoiado sua recuperação?', tipo: 'sim_nao' },
      { id: 'p5', texto: 'Quer um plano para recuperar energia com constância?', tipo: 'sim_nao' },
    ],
    diagnostico: {
      titulo: 'Energia com oscilação ao longo do dia',
      descricao: 'Seu perfil indica potencial de melhoria com ajustes estratégicos de rotina e suporte diário.',
      sintomas: ['Quedas de energia', 'Baixa previsibilidade de desempenho'],
      beneficios: ['Mais estabilidade no dia', 'Melhor foco e disposição'],
      mensagemPositiva: 'Com ajustes simples e consistentes, a energia tende a responder rápido.',
    },
    kitRecomendado: 'energia',
    cta: 'Quero melhorar minha energia',
    tags: ['energia', 'quiz', 'vendas'],
  },
  {
    id: 'avaliacao-inicial',
    nome: 'Avaliação Inicial',
    objetivo: 'Criar linha de base para recomendar o melhor início de plano.',
    perguntas: [
      { id: 'p1', texto: 'Hoje você sente que está distante do seu melhor?', tipo: 'sim_nao' },
      { id: 'p2', texto: 'Sua rotina atual está organizada para evoluir?', tipo: 'sim_nao' },
      { id: 'p3', texto: 'Você consegue manter consistência por pelo menos 7 dias?', tipo: 'sim_nao' },
      { id: 'p4', texto: 'Já tentou antes e perdeu ritmo no meio do caminho?', tipo: 'sim_nao' },
      { id: 'p5', texto: 'Quer começar por um plano mais simples e realista?', tipo: 'sim_nao' },
    ],
    diagnostico: {
      titulo: 'Momento ideal para começo estruturado',
      descricao: 'Seu resultado sugere que um início guiado e simples aumenta muito a chance de aderência.',
      sintomas: ['Falta de direção clara', 'Oscilação de constância'],
      beneficios: ['Começo com foco', 'Mais chance de continuidade'],
      mensagemPositiva: 'Um bom começo muda a trajetória inteira do resultado.',
    },
    kitRecomendado: 'detox',
    cta: 'Quero começar certo',
    tags: ['avaliacao', 'inicio', 'vendas'],
  },
  {
    id: 'desafio-21-dias',
    nome: 'Desafio 21 Dias',
    objetivo: 'Avaliar prontidão para um ciclo de consistência de 21 dias.',
    perguntas: [
      { id: 'p1', texto: 'Você consegue reservar alguns minutos por dia para o seu plano?', tipo: 'sim_nao' },
      { id: 'p2', texto: 'Tem apoio para manter rotina por três semanas?', tipo: 'sim_nao' },
      { id: 'p3', texto: 'Já cumpriu algum desafio com acompanhamento antes?', tipo: 'sim_nao' },
      { id: 'p4', texto: 'Está disposto(a) a seguir um protocolo simples diariamente?', tipo: 'sim_nao' },
      { id: 'p5', texto: 'Quer entrar num desafio com metas claras e acompanhamento?', tipo: 'sim_nao' },
    ],
    diagnostico: {
      titulo: 'Boa prontidão para ciclo de 21 dias',
      descricao: 'Seu perfil combina com um formato de desafio para criar ritmo e consolidar hábitos.',
      sintomas: ['Busca de estrutura', 'Necessidade de compromisso curto e claro'],
      beneficios: ['Consistência guiada', 'Resultado com acompanhamento'],
      mensagemPositiva: '21 dias bem conduzidos podem gerar uma virada consistente.',
    },
    kitRecomendado: 'detox',
    cta: 'Quero entrar no desafio',
    tags: ['desafio', '21dias', 'vendas'],
  },
  {
    id: 'desafio-7-dias',
    nome: 'Desafio 7 Dias',
    objetivo: 'Medir disposição para um primeiro sprint de 7 dias com foco em tração.',
    perguntas: [
      { id: 'p1', texto: 'Você prefere testar mudanças em ciclos curtos?', tipo: 'sim_nao' },
      { id: 'p2', texto: 'Consegue manter disciplina por 7 dias seguidos?', tipo: 'sim_nao' },
      { id: 'p3', texto: 'Está disposto(a) a seguir orientações simples por uma semana?', tipo: 'sim_nao' },
      { id: 'p4', texto: 'Quer medir resultado rápido para ganhar motivação?', tipo: 'sim_nao' },
      { id: 'p5', texto: 'Quer iniciar com um plano de baixa fricção?', tipo: 'sim_nao' },
    ],
    diagnostico: {
      titulo: 'Perfil ideal para sprint de 7 dias',
      descricao: 'Seu padrão combina com uma fase curta de teste para gerar confiança e ritmo.',
      sintomas: ['Preferência por passos curtos', 'Busca por tração inicial'],
      beneficios: ['Começo rápido', 'Clareza de continuidade'],
      mensagemPositiva: 'Sete dias bem executados já ajudam a destravar consistência.',
    },
    kitRecomendado: 'energia',
    cta: 'Quero fazer os 7 dias',
    tags: ['desafio', '7dias', 'vendas'],
  },
  {
    id: 'descubra-perfil-bem-estar',
    nome: 'Descubra seu Perfil de Bem-Estar',
    objetivo: 'Identificar o perfil predominante e orientar plano personalizado.',
    perguntas: [
      { id: 'p1', texto: 'Você sente que seu bem-estar varia muito na semana?', tipo: 'sim_nao' },
      { id: 'p2', texto: 'Sono, alimentação e energia estão alinhados hoje?', tipo: 'sim_nao' },
      { id: 'p3', texto: 'Você sabe qual hábito gera mais impacto no seu caso?', tipo: 'sim_nao' },
      { id: 'p4', texto: 'Consegue manter pequenas rotinas com consistência?', tipo: 'sim_nao' },
      { id: 'p5', texto: 'Quer entender seu perfil para agir com prioridade?', tipo: 'sim_nao' },
    ],
    diagnostico: {
      titulo: 'Perfil de bem-estar em construção',
      descricao: 'Seu resultado indica boa base com necessidade de priorização para evoluir com consistência.',
      sintomas: ['Oscilação de bem-estar', 'Dúvida sobre prioridade'],
      beneficios: ['Plano por perfil', 'Mais direção no dia a dia'],
      mensagemPositiva: 'Quando o plano respeita o perfil, a adesão cresce naturalmente.',
    },
    kitRecomendado: 'energia',
    cta: 'Quero descobrir meu perfil',
    tags: ['perfil', 'bem-estar', 'vendas'],
  },
  {
    id: 'diagnostico-eletrolitos',
    nome: 'Diagnóstico de Eletrólitos',
    objetivo: 'Mapear sinais de desequilíbrio e abrir conversa com orientação prática.',
    perguntas: [
      { id: 'p1', texto: 'Você sente cansaço fora do normal sem explicação clara?', tipo: 'sim_nao' },
      { id: 'p2', texto: 'Tem cãibras ou desconfortos recorrentes?', tipo: 'sim_nao' },
      { id: 'p3', texto: 'Sua hidratação diária está consistente?', tipo: 'sim_nao' },
      { id: 'p4', texto: 'Sente queda de performance em dias corridos?', tipo: 'sim_nao' },
      { id: 'p5', texto: 'Quer ajustar esse quadro com rotina simples?', tipo: 'sim_nao' },
    ],
    diagnostico: {
      titulo: 'Sinais de equilíbrio mineral em atenção',
      descricao: 'As respostas indicam espaço para melhorar equilíbrio e recuperação com ajustes estratégicos.',
      sintomas: ['Oscilação de disposição', 'Sinais de recuperação incompleta'],
      beneficios: ['Mais estabilidade física', 'Rotina com melhor resposta'],
      mensagemPositiva: 'Pequenos ajustes consistentes costumam melhorar o quadro rapidamente.',
    },
    kitRecomendado: 'energia',
    cta: 'Quero ajustar meu equilíbrio',
    tags: ['eletrolitos', 'diagnostico', 'vendas'],
  },
  {
    id: 'diagnostico-parasitose',
    nome: 'Diagnóstico de Parasitose',
    objetivo: 'Levantar sinais de desconforto digestivo e orientar conversa de cuidado funcional.',
    perguntas: [
      { id: 'p1', texto: 'Você tem desconforto digestivo frequente?', tipo: 'sim_nao' },
      { id: 'p2', texto: 'Percebe alteração intestinal sem causa clara?', tipo: 'sim_nao' },
      { id: 'p3', texto: 'Sente fadiga associada a sintomas digestivos?', tipo: 'sim_nao' },
      { id: 'p4', texto: 'Seu padrão alimentar piora os sintomas?', tipo: 'sim_nao' },
      { id: 'p5', texto: 'Quer um plano inicial para organizar esse cenário?', tipo: 'sim_nao' },
    ],
    diagnostico: {
      titulo: 'Sinais digestivos que pedem organização',
      descricao: 'Seu resultado sugere investigar e ajustar hábitos com mais critério e constância.',
      sintomas: ['Desconforto digestivo', 'Oscilação intestinal'],
      beneficios: ['Mais conforto no dia a dia', 'Plano de ajuste gradual'],
      mensagemPositiva: 'Com acompanhamento e constância, o conforto digestivo tende a melhorar.',
    },
    kitRecomendado: 'detox',
    cta: 'Quero organizar minha digestão',
    tags: ['parasitose', 'digestao', 'vendas'],
  },
  {
    id: 'diagnostico-sintomas-intestinais',
    nome: 'Diagnóstico de Sintomas Intestinais',
    objetivo: 'Identificar padrão intestinal e abrir ação prática de melhoria.',
    perguntas: [
      { id: 'p1', texto: 'Você sente estufamento com frequência?', tipo: 'sim_nao' },
      { id: 'p2', texto: 'Seu intestino está regular na maior parte da semana?', tipo: 'sim_nao' },
      { id: 'p3', texto: 'Há relação entre stress e sintomas intestinais?', tipo: 'sim_nao' },
      { id: 'p4', texto: 'Alguns alimentos disparam desconforto?', tipo: 'sim_nao' },
      { id: 'p5', texto: 'Quer um plano simples para reduzir sintomas?', tipo: 'sim_nao' },
    ],
    diagnostico: {
      titulo: 'Padrão intestinal em desequilíbrio leve',
      descricao: 'As respostas mostram sinais de desequilíbrio que podem ser ajustados com estratégia.',
      sintomas: ['Estufamento', 'Irregularidade intestinal'],
      beneficios: ['Mais conforto e leveza', 'Melhor consistência da rotina'],
      mensagemPositiva: 'Ajustes graduais e consistentes costumam trazer alívio progressivo.',
    },
    kitRecomendado: 'detox',
    cta: 'Quero reduzir sintomas intestinais',
    tags: ['intestino', 'diagnostico', 'vendas'],
  },
  {
    id: 'calc-hidratacao',
    nome: 'Calculadora de Água',
    objetivo: 'Quantificar hidratação ideal e facilitar decisão prática de rotina.',
    perguntas: [
      { id: 'peso', texto: 'Qual é seu peso (kg)?', tipo: 'escala', escalaMin: 35, escalaMax: 180 },
      { id: 'atividade', texto: 'Seu nível de atividade é alto?', tipo: 'sim_nao' },
      { id: 'clima', texto: 'Você vive em clima quente na maior parte do tempo?', tipo: 'sim_nao' },
      { id: 'sede', texto: 'Sente sede com frequência durante o dia?', tipo: 'sim_nao' },
      { id: 'rotina', texto: 'Quer uma meta diária simples de seguir?', tipo: 'sim_nao' },
    ],
    diagnostico: {
      titulo: 'Hidratação com margem de melhoria',
      descricao: 'Seu resultado indica oportunidade de melhorar hidratação e resposta da rotina.',
      sintomas: ['Consumo abaixo do ideal', 'Oscilação de disposição'],
      beneficios: ['Meta clara de água', 'Mais energia e foco ao longo do dia'],
      mensagemPositiva: 'A hidratação correta é uma das mudanças mais rápidas de aplicar.',
    },
    kitRecomendado: 'energia',
    cta: 'Quero minha meta de hidratação',
    tags: ['calculadora', 'agua', 'vendas'],
  },
  {
    id: 'calc-calorias',
    nome: 'Calculadora de Calorias',
    objetivo: 'Estimar necessidade calórica e orientar próximos passos de forma acessível.',
    perguntas: [
      { id: 'idade', texto: 'Qual sua faixa de idade?', tipo: 'multipla_escolha', opcoes: ['18-29', '30-39', '40-49', '50+'] },
      { id: 'peso', texto: 'Qual seu peso aproximado?', tipo: 'multipla_escolha', opcoes: ['até 60kg', '61-80kg', '81-100kg', 'acima de 100kg'] },
      { id: 'atividade', texto: 'Seu nível de atividade física atual?', tipo: 'multipla_escolha', opcoes: ['baixo', 'moderado', 'alto'] },
      { id: 'objetivo', texto: 'Seu objetivo principal hoje?', tipo: 'multipla_escolha', opcoes: ['emagrecer', 'manter', 'ganhar energia'] },
      { id: 'clareza', texto: 'Quer uma referência simples para começar?', tipo: 'sim_nao' },
    ],
    diagnostico: {
      titulo: 'Base calórica para decisão mais inteligente',
      descricao: 'Seu perfil beneficia de uma referência prática para ajustar alimentação com mais precisão.',
      sintomas: ['Incerteza sobre consumo ideal', 'Ajustes sem critério'],
      beneficios: ['Mais clareza na rotina alimentar', 'Decisões com base em referência'],
      mensagemPositiva: 'Com referência certa, fica mais fácil manter consistência sem radicalismo.',
    },
    kitRecomendado: 'detox',
    cta: 'Quero minha referência calórica',
    tags: ['calculadora', 'calorias', 'vendas'],
  },
  {
    id: 'calc-imc',
    nome: 'Calculadora de IMC',
    objetivo: 'Oferecer indicador inicial para conversa e plano personalizado.',
    perguntas: [
      { id: 'peso', texto: 'Qual seu peso (kg)?', tipo: 'escala', escalaMin: 35, escalaMax: 180 },
      { id: 'altura', texto: 'Qual sua altura (cm)?', tipo: 'escala', escalaMin: 140, escalaMax: 210 },
      { id: 'rotina', texto: 'Consegue manter rotina semanal de cuidado?', tipo: 'sim_nao' },
      { id: 'energia', texto: 'Sua energia atual está abaixo do que gostaria?', tipo: 'sim_nao' },
      { id: 'objetivo', texto: 'Quer usar esse indicador para orientar seus próximos passos?', tipo: 'sim_nao' },
    ],
    diagnostico: {
      titulo: 'Indicador inicial para direcionar evolução',
      descricao: 'Seu resultado ajuda a definir um ponto de partida mais claro para a próxima fase.',
      sintomas: ['Falta de indicador de base', 'Dificuldade em priorizar ação'],
      beneficios: ['Direção inicial objetiva', 'Mais clareza para o plano'],
      mensagemPositiva: 'Ponto de partida claro acelera decisões melhores.',
    },
    kitRecomendado: 'detox',
    cta: 'Quero meu ponto de partida',
    tags: ['calculadora', 'imc', 'vendas'],
  },
  {
    id: 'calc-proteina',
    nome: 'Calculadora de Proteína',
    objetivo: 'Estimar consumo proteico e orientar ajuste simples da alimentação.',
    perguntas: [
      { id: 'peso', texto: 'Qual seu peso aproximado?', tipo: 'multipla_escolha', opcoes: ['até 60kg', '61-80kg', '81-100kg', 'acima de 100kg'] },
      { id: 'objetivo', texto: 'Qual objetivo principal?', tipo: 'multipla_escolha', opcoes: ['emagrecer', 'manter', 'ganhar massa'] },
      { id: 'atividade', texto: 'Seu nível de atividade é regular?', tipo: 'sim_nao' },
      { id: 'fome', texto: 'Sente fome entre refeições com frequência?', tipo: 'sim_nao' },
      { id: 'ajuste', texto: 'Quer um ajuste de proteína fácil de aplicar?', tipo: 'sim_nao' },
    ],
    diagnostico: {
      titulo: 'Proteína com potencial de ajuste',
      descricao: 'Seu perfil pode ganhar mais saciedade e resultado com ajuste proteico estratégico.',
      sintomas: ['Saciedade baixa', 'Consumo proteico irregular'],
      beneficios: ['Mais saciedade', 'Melhor resposta da rotina alimentar'],
      mensagemPositiva: 'Ajustes simples de proteína costumam gerar boa resposta prática.',
    },
    kitRecomendado: 'detox',
    cta: 'Quero ajustar minha proteína',
    tags: ['calculadora', 'proteina', 'vendas'],
  },
  {
    id: 'pronto-emagrecer',
    nome: 'Pronto para Emagrecer com Saúde?',
    objetivo: 'Medir prontidão para um plano de emagrecimento com foco em consistência.',
    perguntas: [
      { id: 'p1', texto: 'Você está disposto(a) a manter ajustes simples por algumas semanas?', tipo: 'sim_nao' },
      { id: 'p2', texto: 'Consegue organizar minimamente alimentação e hidratação?', tipo: 'sim_nao' },
      { id: 'p3', texto: 'Está aberto(a) a acompanhamento para manter ritmo?', tipo: 'sim_nao' },
      { id: 'p4', texto: 'Seu maior desafio hoje é constância?', tipo: 'sim_nao' },
      { id: 'p5', texto: 'Quer um plano realista para começar agora?', tipo: 'sim_nao' },
    ],
    diagnostico: {
      titulo: 'Prontidão em evolução para emagrecer com saúde',
      descricao: 'Seu resultado mostra boa base, com necessidade de estratégia prática para manter aderência.',
      sintomas: ['Oscilação de disciplina', 'Início sem continuidade'],
      beneficios: ['Plano viável', 'Mais consistência no processo'],
      mensagemPositiva: 'Com método certo, a evolução pode ser sustentável sem extremos.',
    },
    kitRecomendado: 'detox',
    cta: 'Quero começar com estratégia',
    tags: ['emagrecimento', 'prontidao', 'vendas'],
  },
  {
    id: 'avaliacao-fome-emocional',
    nome: 'Avaliação de Fome Emocional',
    objetivo: 'Mapear gatilhos emocionais e orientar ajustes práticos de rotina.',
    perguntas: [
      { id: 'p1', texto: 'Você come para aliviar stress ou ansiedade?', tipo: 'sim_nao' },
      { id: 'p2', texto: 'Percebe perda de controlo em momentos emocionais?', tipo: 'sim_nao' },
      { id: 'p3', texto: 'Depois de comer, sente culpa com frequência?', tipo: 'sim_nao' },
      { id: 'p4', texto: 'Sua fome física e emocional se confundem no dia a dia?', tipo: 'sim_nao' },
      { id: 'p5', texto: 'Quer reduzir esse ciclo com estratégia simples?', tipo: 'sim_nao' },
    ],
    diagnostico: {
      titulo: 'Fome emocional com impacto na consistência',
      descricao: 'Seu padrão indica gatilhos emocionais que podem ser organizados com abordagem prática.',
      sintomas: ['Compensação alimentar', 'Culpa e oscilação'],
      beneficios: ['Mais autocontrolo', 'Rotina alimentar mais previsível'],
      mensagemPositiva: 'Com leitura dos gatilhos, fica mais fácil manter equilíbrio.',
    },
    kitRecomendado: 'detox',
    cta: 'Quero reduzir fome emocional',
    tags: ['fome-emocional', 'avaliacao', 'vendas'],
  },
  {
    id: 'avaliacao-intolerancias-sensibilidades',
    nome: 'Avaliação de Intolerâncias/Sensibilidades',
    objetivo: 'Identificar sinais de sensibilidade alimentar e orientar ajustes iniciais.',
    perguntas: [
      { id: 'p1', texto: 'Você sente desconforto após certos alimentos?', tipo: 'sim_nao' },
      { id: 'p2', texto: 'Percebe estufamento, gases ou indisposição recorrente?', tipo: 'sim_nao' },
      { id: 'p3', texto: 'Consegue reconhecer quais alimentos pioram os sintomas?', tipo: 'sim_nao' },
      { id: 'p4', texto: 'Esses sinais afetam sua energia diária?', tipo: 'sim_nao' },
      { id: 'p5', texto: 'Quer um plano inicial para reduzir gatilhos?', tipo: 'sim_nao' },
    ],
    diagnostico: {
      titulo: 'Sensibilidade alimentar em observação',
      descricao: 'Seu resultado sugere organizar gatilhos e rotina para reduzir desconfortos.',
      sintomas: ['Sinais digestivos recorrentes', 'Baixa previsibilidade alimentar'],
      beneficios: ['Mais conforto pós-refeição', 'Plano alimentar mais estável'],
      mensagemPositiva: 'Com ajustes graduais, o corpo costuma responder melhor.',
    },
    kitRecomendado: 'detox',
    cta: 'Quero reduzir sensibilidades',
    tags: ['intolerancia', 'sensibilidades', 'vendas'],
  },
  {
    id: 'avaliacao-perfil-metabolico',
    nome: 'Avaliação do Perfil Metabólico',
    objetivo: 'Identificar padrão metabólico predominante para orientar plano personalizado.',
    perguntas: [
      { id: 'p1', texto: 'Você sente facilidade para acumular peso?', tipo: 'sim_nao' },
      { id: 'p2', texto: 'Sua energia oscila bastante ao longo do dia?', tipo: 'sim_nao' },
      { id: 'p3', texto: 'Tem dificuldade para manter ritmo de emagrecimento?', tipo: 'sim_nao' },
      { id: 'p4', texto: 'Seu sono e stress parecem afetar seu metabolismo?', tipo: 'sim_nao' },
      { id: 'p5', texto: 'Quer uma estratégia mais alinhada ao seu perfil?', tipo: 'sim_nao' },
    ],
    diagnostico: {
      titulo: 'Perfil metabólico com oportunidade de ajuste',
      descricao: 'Seu resultado indica que personalizar estratégia pode acelerar a resposta do corpo.',
      sintomas: ['Resposta metabólica irregular', 'Dificuldade de constância no resultado'],
      beneficios: ['Plano mais assertivo', 'Melhor previsibilidade de evolução'],
      mensagemPositiva: 'Quando o plano respeita o perfil metabólico, os resultados tendem a sustentar melhor.',
    },
    kitRecomendado: 'detox',
    cta: 'Quero meu plano por perfil metabólico',
    tags: ['metabolico', 'avaliacao', 'vendas'],
  },
  {
    id: 'avaliacao-sono-energia',
    nome: 'Avaliação do Sono e Energia',
    objetivo: 'Relacionar qualidade de sono com energia diária e orientar ações práticas.',
    perguntas: [
      { id: 'p1', texto: 'Você acorda com sensação de recuperação real?', tipo: 'sim_nao' },
      { id: 'p2', texto: 'Seu sono é consistente em horários e duração?', tipo: 'sim_nao' },
      { id: 'p3', texto: 'Sente queda de energia apesar de dormir horas suficientes?', tipo: 'sim_nao' },
      { id: 'p4', texto: 'Stress noturno afeta seu descanso?', tipo: 'sim_nao' },
      { id: 'p5', texto: 'Quer melhorar energia começando pelo sono?', tipo: 'sim_nao' },
    ],
    diagnostico: {
      titulo: 'Sono em ajuste para recuperar energia',
      descricao: 'Seu perfil mostra que otimizar descanso pode elevar muito sua disposição diária.',
      sintomas: ['Recuperação incompleta', 'Energia baixa ao acordar'],
      beneficios: ['Mais energia matinal', 'Melhor foco e rendimento'],
      mensagemPositiva: 'Pequenos ajustes no sono costumam trazer ganhos rápidos de energia.',
    },
    kitRecomendado: 'energia',
    cta: 'Quero ajustar sono e energia',
    tags: ['sono', 'energia', 'avaliacao', 'vendas'],
  },
]
