import type { FluxoCliente } from '@/types/wellness-system'

/**
 * Bloco 3 de Vendas no Pro Líderes:
 * ferramentas clássicas do Wellness reestruturadas para a biblioteca prefixada.
 */
export const proLideresSalesBlock3Fluxos: FluxoCliente[] = [
  {
    id: 'retencao-liquidos',
    nome: 'Teste de Retenção de Líquidos',
    objetivo: 'Identificar sinais de retenção e abrir conversa consultiva sobre hábitos e rotina.',
    perguntas: [
      { id: 'p1', texto: 'Você sente inchaço com frequência ao fim do dia?', tipo: 'sim_nao' },
      { id: 'p2', texto: 'Acorda com sensação de rosto ou mãos inchados?', tipo: 'sim_nao' },
      { id: 'p3', texto: 'Sua hidratação diária está consistente?', tipo: 'sim_nao' },
      { id: 'p4', texto: 'Percebe piora em dias de alimentação mais pesada?', tipo: 'sim_nao' },
      { id: 'p5', texto: 'Quer um plano simples para reduzir esse desconforto?', tipo: 'sim_nao' },
    ],
    diagnostico: {
      titulo: 'Sinais de retenção que merecem ajuste',
      descricao: 'As respostas indicam que pequenos ajustes podem melhorar conforto e leveza no dia a dia.',
      sintomas: ['Inchaço recorrente', 'Oscilação de bem-estar ao longo do dia'],
      beneficios: ['Mais leveza na rotina', 'Estratégia simples e sustentável'],
      mensagemPositiva: 'Com orientação certa, é comum perceber evolução já nas primeiras semanas.',
    },
    kitRecomendado: 'detox',
    cta: 'Quero ajustar minha rotina',
    tags: ['retencao', 'inchaco', 'vendas', 'wellness'],
  },
  {
    id: 'conhece-seu-corpo',
    nome: 'Você conhece o seu corpo?',
    objetivo: 'Aumentar percepção corporal e direcionar para uma conversa prática de evolução.',
    perguntas: [
      { id: 'p1', texto: 'Você percebe claramente como seu corpo responde à rotina?', tipo: 'sim_nao' },
      { id: 'p2', texto: 'Consegue identificar seus principais gatilhos de cansaço?', tipo: 'sim_nao' },
      { id: 'p3', texto: 'Sua alimentação acompanha seu nível de atividade?', tipo: 'sim_nao' },
      { id: 'p4', texto: 'Você monitoriza algum indicador simples de bem-estar?', tipo: 'sim_nao' },
      { id: 'p5', texto: 'Gostaria de ter mais clareza sobre o que ajustar primeiro?', tipo: 'sim_nao' },
    ],
    diagnostico: {
      titulo: 'Clareza corporal parcial',
      descricao: 'Há sinais de que você pode ganhar resultado com mais consciência e rotina direcionada.',
      sintomas: ['Baixa previsibilidade de energia', 'Dúvidas sobre prioridade de ajustes'],
      beneficios: ['Mais clareza nas decisões', 'Plano mais assertivo para sua realidade'],
      mensagemPositiva: 'Quando há clareza, a consistência fica mais fácil e o resultado aparece.',
    },
    kitRecomendado: 'energia',
    cta: 'Quero um plano mais claro',
    tags: ['corpo', 'clareza', 'vendas'],
  },
  {
    id: 'disciplinado-emocional-comida',
    nome: 'Você é mais disciplinado ou emocional com a comida?',
    objetivo: 'Mapear padrão alimentar para orientar ação prática e sustentável.',
    perguntas: [
      { id: 'p1', texto: 'Você come por fome real na maior parte do tempo?', tipo: 'sim_nao' },
      { id: 'p2', texto: 'Situações de stress mudam sua alimentação?', tipo: 'sim_nao' },
      { id: 'p3', texto: 'Você consegue manter um plano sem extremos?', tipo: 'sim_nao' },
      { id: 'p4', texto: 'Tem episódios de compensação com doce ou excesso?', tipo: 'sim_nao' },
      { id: 'p5', texto: 'Quer reduzir o impacto emocional nas escolhas?', tipo: 'sim_nao' },
    ],
    diagnostico: {
      titulo: 'Predomínio emocional nas escolhas',
      descricao: 'Seu padrão sugere espaço para ganhar controle sem rigidez, com ajustes inteligentes.',
      sintomas: ['Oscilação alimentar por emoção', 'Dificuldade de constância'],
      beneficios: ['Mais equilíbrio na rotina', 'Menos culpa e mais previsibilidade'],
      mensagemPositiva: 'Com método simples, disciplina e liberdade podem coexistir.',
    },
    kitRecomendado: 'detox',
    cta: 'Quero equilíbrio alimentar',
    tags: ['fome-emocional', 'alimentacao', 'vendas'],
  },
  {
    id: 'nutrido-vs-alimentado',
    nome: 'Você está nutrido ou apenas alimentado?',
    objetivo: 'Diferenciar volume de comida vs qualidade nutricional e orientar próximos passos.',
    perguntas: [
      { id: 'p1', texto: 'Sua alimentação diária tem variedade de nutrientes?', tipo: 'sim_nao' },
      { id: 'p2', texto: 'Você sente energia estável após as refeições?', tipo: 'sim_nao' },
      { id: 'p3', texto: 'Consegue manter foco no período da tarde?', tipo: 'sim_nao' },
      { id: 'p4', texto: 'Seu sono parece ligado ao que você come?', tipo: 'sim_nao' },
      { id: 'p5', texto: 'Quer uma rota simples para melhorar nutrição?', tipo: 'sim_nao' },
    ],
    diagnostico: {
      titulo: 'Alimentado, mas com nutrição otimável',
      descricao: 'Você já faz parte do caminho, mas ainda há espaço para melhorar qualidade e resultado.',
      sintomas: ['Energia irregular', 'Sinais de baixa densidade nutricional'],
      beneficios: ['Mais disposição', 'Melhor resposta do corpo à rotina'],
      mensagemPositiva: 'Pequenas trocas estratégicas geram impacto real no dia a dia.',
    },
    kitRecomendado: 'detox',
    cta: 'Quero melhorar minha nutrição',
    tags: ['nutricao', 'vendas'],
  },
  {
    id: 'alimentacao-rotina',
    nome: 'Você está se alimentando conforme sua rotina?',
    objetivo: 'Alinhar padrão alimentar com rotina real para aumentar consistência.',
    perguntas: [
      { id: 'p1', texto: 'Você costuma saltar refeições por falta de tempo?', tipo: 'sim_nao' },
      { id: 'p2', texto: 'Sua rotina permite planeamento alimentar básico?', tipo: 'sim_nao' },
      { id: 'p3', texto: 'Você sente queda de energia em horários previsíveis?', tipo: 'sim_nao' },
      { id: 'p4', texto: 'Consegue manter padrão nos dias mais corridos?', tipo: 'sim_nao' },
      { id: 'p5', texto: 'Quer um plano adaptado ao seu ritmo real?', tipo: 'sim_nao' },
    ],
    diagnostico: {
      titulo: 'Desalinhamento entre rotina e alimentação',
      descricao: 'Seu resultado indica que o principal ajuste está no encaixe da estratégia ao seu dia.',
      sintomas: ['Oscilação de energia', 'Baixa aderência em dias corridos'],
      beneficios: ['Mais consistência', 'Plano que cabe na sua realidade'],
      mensagemPositiva: 'Quando o plano encaixa na rotina, manter fica mais fácil.',
    },
    kitRecomendado: 'energia',
    cta: 'Quero alinhar com minha rotina',
    tags: ['rotina', 'alimentacao', 'vendas'],
  },
  {
    id: 'tipo-fome',
    nome: 'Qual é seu tipo de fome?',
    objetivo: 'Identificar tipo de fome predominante e orientar ação prática.',
    perguntas: [
      { id: 'p1', texto: 'Você sente fome física em horários previsíveis?', tipo: 'sim_nao' },
      { id: 'p2', texto: 'A vontade de comer surge em momentos emocionais?', tipo: 'sim_nao' },
      { id: 'p3', texto: 'Sente vontade por alimentos específicos com frequência?', tipo: 'sim_nao' },
      { id: 'p4', texto: 'Depois de comer, a saciedade dura pouco?', tipo: 'sim_nao' },
      { id: 'p5', texto: 'Quer aprender a diferenciar gatilho e necessidade?', tipo: 'sim_nao' },
    ],
    diagnostico: {
      titulo: 'Fome mista com gatilhos emocionais',
      descricao: 'O padrão sugere que reconhecer o gatilho certo é a chave para ganhar controlo.',
      sintomas: ['Compulsos pontuais', 'Dificuldade de leitura da fome'],
      beneficios: ['Mais autocontrolo', 'Escolhas mais conscientes'],
      mensagemPositiva: 'Com leitura correta da fome, a rotina fica mais leve e consistente.',
    },
    kitRecomendado: 'detox',
    cta: 'Quero identificar meu tipo de fome',
    tags: ['fome', 'emocional', 'vendas'],
  },
  {
    id: 'perfil-intestino',
    nome: 'Qual é seu perfil de intestino?',
    objetivo: 'Mapear sinais digestivos e orientar conversa de melhoria gradual.',
    perguntas: [
      { id: 'p1', texto: 'Seu intestino funciona regularmente ao longo da semana?', tipo: 'sim_nao' },
      { id: 'p2', texto: 'Você sente estufamento após refeições?', tipo: 'sim_nao' },
      { id: 'p3', texto: 'Percebe sensibilidade com alguns alimentos?', tipo: 'sim_nao' },
      { id: 'p4', texto: 'Sua hidratação e fibras estão consistentes?', tipo: 'sim_nao' },
      { id: 'p5', texto: 'Quer melhorar conforto digestivo com estratégia simples?', tipo: 'sim_nao' },
    ],
    diagnostico: {
      titulo: 'Perfil intestinal sensível',
      descricao: 'Há sinais de que ajustes simples podem melhorar digestão e bem-estar geral.',
      sintomas: ['Estufamento frequente', 'Irregularidade digestiva'],
      beneficios: ['Mais conforto intestinal', 'Melhor energia diária'],
      mensagemPositiva: 'Com abordagem gradual, o intestino tende a responder muito bem.',
    },
    kitRecomendado: 'detox',
    cta: 'Quero cuidar do meu intestino',
    tags: ['intestino', 'digestao', 'vendas'],
  },
  {
    id: 'quiz-bem-estar',
    nome: 'Quiz de Bem-Estar',
    objetivo: 'Avaliar equilíbrio geral de hábitos e gerar conversa de melhoria prática.',
    perguntas: [
      { id: 'p1', texto: 'Você sente que sua rotina atual sustenta seu bem-estar?', tipo: 'sim_nao' },
      { id: 'p2', texto: 'Seu nível de energia acompanha suas metas?', tipo: 'sim_nao' },
      { id: 'p3', texto: 'Sono, alimentação e hidratação estão consistentes?', tipo: 'sim_nao' },
      { id: 'p4', texto: 'Você consegue manter constância na maior parte da semana?', tipo: 'sim_nao' },
      { id: 'p5', texto: 'Quer um próximo passo simples e aplicável?', tipo: 'sim_nao' },
    ],
    diagnostico: {
      titulo: 'Bem-estar com espaço de otimização',
      descricao: 'Seu resultado aponta boa base, com ajustes-chave para ganhar consistência e resultado.',
      sintomas: ['Oscilações de rotina', 'Resultados abaixo do potencial'],
      beneficios: ['Mais estabilidade', 'Plano claro de evolução'],
      mensagemPositiva: 'Com direção e constância, a evolução tende a acelerar.',
    },
    kitRecomendado: 'energia',
    cta: 'Quero melhorar meu bem-estar',
    tags: ['bem-estar', 'rotina', 'vendas'],
  },
  {
    id: 'quiz-perfil-nutricional',
    nome: 'Quiz de Perfil Nutricional',
    objetivo: 'Diagnosticar padrão nutricional e orientar recomendação personalizada.',
    perguntas: [
      { id: 'p1', texto: 'Sua alimentação é equilibrada durante a semana?', tipo: 'sim_nao' },
      { id: 'p2', texto: 'Você sente fome fora de horário com frequência?', tipo: 'sim_nao' },
      { id: 'p3', texto: 'Seu consumo de água está adequado?', tipo: 'sim_nao' },
      { id: 'p4', texto: 'Você percebe impacto da alimentação na energia?', tipo: 'sim_nao' },
      { id: 'p5', texto: 'Quer um plano nutricional mais simples de seguir?', tipo: 'sim_nao' },
    ],
    diagnostico: {
      titulo: 'Perfil nutricional em ajuste',
      descricao: 'As respostas sugerem ganhos importantes com pequenas correções estratégicas.',
      sintomas: ['Padrão alimentar irregular', 'Oscilação de energia'],
      beneficios: ['Mais qualidade nutricional', 'Rotina mais fácil de manter'],
      mensagemPositiva: 'Com poucos ajustes, é possível subir o nível da rotina rapidamente.',
    },
    kitRecomendado: 'detox',
    cta: 'Quero ajustar meu perfil nutricional',
    tags: ['nutricao', 'perfil', 'vendas'],
  },
  {
    id: 'quiz-detox',
    nome: 'Quiz Detox',
    objetivo: 'Mapear sinais de sobrecarga e orientar plano de reorganização.',
    perguntas: [
      { id: 'p1', texto: 'Você sente inchaço ou peso corporal frequente?', tipo: 'sim_nao' },
      { id: 'p2', texto: 'Sua energia varia muito ao longo do dia?', tipo: 'sim_nao' },
      { id: 'p3', texto: 'Seu intestino está irregular ultimamente?', tipo: 'sim_nao' },
      { id: 'p4', texto: 'Você sente dificuldade para manter leveza e foco?', tipo: 'sim_nao' },
      { id: 'p5', texto: 'Quer uma estratégia simples para começar um reset?', tipo: 'sim_nao' },
    ],
    diagnostico: {
      titulo: 'Sinais de sobrecarga funcional',
      descricao: 'Seu resultado indica que um plano de reset pode ajudar a recuperar leveza e ritmo.',
      sintomas: ['Sensação de peso', 'Energia instável'],
      beneficios: ['Mais leveza e disposição', 'Melhor resposta da rotina'],
      mensagemPositiva: 'Quando o corpo volta ao equilíbrio, o dia rende melhor com menos esforço.',
    },
    kitRecomendado: 'detox',
    cta: 'Quero iniciar meu reset',
    tags: ['detox', 'vendas', 'reset'],
  },
]
