/**
 * DIAGNÓSTICOS: Avaliação de Intolerância Alimentar - ÁREA NUTRI
 * 
 * Diagnósticos focados em identificar intolerâncias e sensibilidades alimentares
 * que estimulam contato com nutricionista profissional
 */

import { DiagnosticosPorFerramenta } from '../types'

export const avaliacaoIntoleranciaDiagnosticos: DiagnosticosPorFerramenta = {
  nutri: {
    altaSuspeitaIntolerancia: {
      diagnostico: '📋 DIAGNÓSTICO: Seus sintomas indicam alta suspeita de intolerâncias ou sensibilidades alimentares. Um acompanhamento nutricional especializado é essencial para identificar os alimentos problemáticos e criar um plano personalizado que melhore sua qualidade de vida.',
      causaRaiz: '🔍 CAUSA RAIZ: Intolerâncias alimentares podem causar sintomas digestivos, inchaço, gases, dores abdominais e até mesmo fadiga. Estudos mostram que até 20% da população pode ter alguma intolerância alimentar não diagnosticada. Quando não identificadas, essas sensibilidades podem impactar negativamente a qualidade de vida, energia e bem-estar geral. Uma avaliação nutricional completa identifica padrões alimentares problemáticos, cria um plano de eliminação controlado e garante nutrição adequada mesmo com restrições alimentares.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Busque avaliação nutricional especializada para identificar suas intolerâncias alimentares. Uma nutricionista pode criar um plano de eliminação controlado, identificar alimentos problemáticos e garantir nutrição adequada mesmo com restrições. Evite eliminar alimentos por conta própria — isso pode levar a deficiências nutricionais.',
      plano7Dias: '📅 PLANO 7 DIAS: Protocolo inicial de eliminação controlada com identificação de alimentos problemáticos, plano alimentar adequado ao seu perfil de intolerância, cronograma de reintrodução controlada, estratégias para manter nutrição adequada mesmo com restrições e acompanhamento para monitorar melhorias. O suporte nutricional é fundamental para uma transição segura e eficaz.',
      suplementacao: '💊 SUPLEMENTAÇÃO: A necessidade só é definida após avaliação nutricional completa. Multivitamínicos, probióticos e enzimas digestivas podem ser considerados quando há indicação, mas sempre de acordo com a individualidade biológica e necessidades específicas identificadas na consulta.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um plano alimentar personalizado considera suas intolerâncias identificadas. Priorize alimentos seguros, evite alimentos problemáticos e mantenha variedade nutricional mesmo com restrições. Uma nutricionista ajusta quantidades e combinações ideais para você, garantindo nutrição completa mesmo com restrições alimentares.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Sua qualidade de vida pode melhorar significativamente ao identificar e tratar adequadamente suas intolerâncias alimentares. Agende uma avaliação nutricional para receber um acompanhamento especializado com estratégias personalizadas. Descubra como um plano adequado pode transformar seu bem-estar.'
    },
    intoleranciaModerada: {
      diagnostico: '📋 DIAGNÓSTICO: Você apresenta alguns sinais que podem indicar sensibilidade alimentar moderada. Um acompanhamento nutricional pode ajudar a identificar padrões e criar estratégias que otimizem seu bem-estar digestivo.',
      causaRaiz: '🔍 CAUSA RAIZ: Sensibilidades alimentares moderadas podem causar sintomas intermitentes que muitas vezes passam despercebidos ou são atribuídos a outras causas. Pesquisas indicam que muitas pessoas vivem com desconfortos leves a moderados sem saber que são causados por alimentos específicos. Uma avaliação nutricional completa identifica esses padrões sutis, cria um plano alimentar otimizado e fornece orientações para melhorar sua qualidade de vida e prevenir que sensibilidades se tornem mais severas.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Busque avaliação nutricional para uma análise personalizada que identifica padrões alimentares que causam desconforto. Uma nutricionista pode criar estratégias práticas para otimizar sua alimentação, ajustar plano alimentar adequado e acompanhar sua evolução. Com pequenos ajustes personalizados, você pode melhorar significativamente seu bem-estar digestivo.',
      plano7Dias: '📅 PLANO 7 DIAS: Protocolo inicial com identificação de padrões alimentares problemáticos, estratégias práticas para otimizar sua alimentação, plano alimentar adequado, cronograma de observação e ajustes, e acompanhamento para monitorar melhorias. O acompanhamento nutricional ajuda a identificar conexões sutis entre alimentos e sintomas.',
      suplementacao: '💊 SUPLEMENTAÇÃO: A necessidade só é definida após avaliação nutricional. Probióticos, enzimas digestivas e multivitamínicos podem ser considerados quando há indicação, mas sempre de acordo com a individualidade biológica e necessidades específicas identificadas na consulta.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um plano alimentar personalizado considera suas sensibilidades moderadas. Priorize alimentos bem tolerados, estratégias para identificar alimentos problemáticos e combinações que melhoram digestão. Uma nutricionista ajusta quantidades e combinações ideais para você, criando hábitos alimentares que promovem bem-estar contínuo.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Com um acompanhamento nutricional personalizado, você pode otimizar sua alimentação e melhorar seu bem-estar digestivo. Agende uma avaliação nutricional para receber estratégias práticas adequadas ao seu perfil. Pequenos ajustes podem fazer grande diferença na sua qualidade de vida!'
    },
    baixaProbabilidadeIntolerancia: {
      diagnostico: '📋 DIAGNÓSTICO: Você parece ter boa tolerância alimentar. Mesmo assim, um acompanhamento nutricional preventivo pode ajudar a otimizar sua alimentação e prevenir futuras sensibilidades, mantendo seu bem-estar em alta.',
      causaRaiz: '🔍 CAUSA RAIZ: Ter boa tolerância alimentar é um grande ativo, mas mesmo pessoas com boa digestão podem se beneficiar de otimizações nutricionais preventivas. Pesquisas mostram que hábitos alimentares inadequados ao longo do tempo podem levar ao desenvolvimento de sensibilidades. Uma avaliação nutricional completa cria estratégias preventivas personalizadas e fornece orientações para manter seu bem-estar em longo prazo. A prevenção é sempre melhor que o tratamento.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Considere uma avaliação nutricional preventiva para otimizar sua alimentação e saúde digestiva. Uma nutricionista pode criar estratégias personalizadas, ajustar plano alimentar adequado e fornecer orientações para manter sua excelente tolerância alimentar ao longo do tempo. A prevenção garante qualidade de vida contínua.',
      plano7Dias: '📅 PLANO 7 DIAS: Protocolo preventivo com otimização nutricional, estratégias para manter saúde digestiva, plano alimentar adequado, orientações sobre combinações alimentares ideais e acompanhamento para garantir que você mantenha sua excelente tolerância alimentar. A prevenção é a melhor estratégia.',
      suplementacao: '💊 SUPLEMENTAÇÃO: A necessidade só é definida após avaliação nutricional. Probióticos preventivos e multivitamínicos podem ser considerados quando há indicação, mas sempre de acordo com a individualidade biológica e necessidades específicas identificadas na consulta.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um plano alimentar preventivo considera sua boa tolerância atual. Priorize otimização nutricional, estratégias para manter excelente tolerância alimentar e combinações alimentares ideais. Uma nutricionista ajusta quantidades e combinações para manter sua saúde digestiva em excelência.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Mantenha sua excelente tolerância alimentar com estratégias preventivas personalizadas. Agende uma avaliação nutricional para receber orientações adequadas ao seu perfil. A prevenção é o melhor investimento para sua saúde a longo prazo!'
    }
  }
}

