/**
 * DIAGNÓSTICOS: Diagnóstico de Sintomas Intestinais - ÁREA NUTRI
 * 
 * Diagnósticos focados em identificar problemas intestinais
 * que estimulam contato com nutricionista profissional
 */

import { DiagnosticosPorFerramenta } from '../types'

export const diagnosticoSintomasIntestinaisDiagnosticos: DiagnosticosPorFerramenta = {
  nutri: {
    problemasIntestinais: {
      diagnostico: '📋 DIAGNÓSTICO: Seus sintomas indicam problemas intestinais que precisam de atenção. Um acompanhamento nutricional especializado é essencial para identificar causas e criar estratégias eficazes que melhorem significativamente sua saúde intestinal e qualidade de vida.',
      causaRaiz: '🔍 CAUSA RAIZ: Problemas intestinais podem ser causados por diversos fatores como desequilíbrios na microbiota, intolerâncias alimentares, estresse, falta de fibras, ou até mesmo problemas de digestão. Estudos mostram que até 60% das pessoas têm problemas digestivos não diagnosticados que impactam negativamente sua qualidade de vida, energia e bem-estar geral. Quando não identificados e tratados, esses problemas podem piorar ao longo do tempo. Uma avaliação nutricional completa identifica padrões alimentares problemáticos, cria um plano personalizado de saúde digestiva e fornece orientações para restaurar sua saúde intestinal.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Busque avaliação nutricional especializada para identificar e tratar seus problemas intestinais. Uma nutricionista pode criar um plano personalizado que inclui estratégias nutricionais otimizadas, protocolos adequados e acompanhamento constante. Evite abordagens genéricas — cada pessoa tem causas específicas que requerem estratégias personalizadas.',
      plano7Dias: '📅 PLANO 7 DIAS: Protocolo inicial de recuperação da saúde intestinal com estratégias nutricionais otimizadas para digestão, plano alimentar adequado, cronograma detalhado, acompanhamento para monitorar melhorias e ajustes conforme sua resposta individual. O suporte nutricional é fundamental para uma recuperação segura e eficaz.',
      suplementacao: '💊 SUPLEMENTAÇÃO: A necessidade só é definida após avaliação nutricional completa. Probióticos, fibras e enzimas digestivas podem ser considerados quando há indicação, mas sempre de acordo com a individualidade biológica e necessidades específicas identificadas na consulta.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um plano alimentar personalizado considera seus problemas intestinais. Priorize alimentos ricos em fibras, estratégias de combinação de alimentos para melhor digestão, alimentos probióticos naturais e combinações ideais. Uma nutricionista ajusta quantidades e combinações ideais para você, criando hábitos alimentares que mantêm intestino saudável.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Sua qualidade de vida pode melhorar significativamente ao tratar adequadamente seus problemas intestinais. Agende uma avaliação nutricional para receber um acompanhamento especializado com estratégias personalizadas. Descubra como um plano adequado pode restaurar sua saúde intestinal.'
    },
    problemasModerados: {
      diagnostico: '📋 DIAGNÓSTICO: Você apresenta alguns sinais que podem indicar problemas intestinais moderados. Um acompanhamento nutricional pode ajudar a otimizar sua saúde digestiva e prevenir problemas futuros.',
      causaRaiz: '🔍 CAUSA RAIZ: Problemas intestinais moderados podem causar sintomas intermitentes que muitas vezes passam despercebidos ou são atribuídos a outras causas como cansaço ou má alimentação. Pesquisas indicam que muitas pessoas vivem com desequilíbrios digestivos sutis sem saber que são causados por padrões alimentares ou falta de nutrientes adequados. Uma avaliação nutricional completa identifica esses padrões sutis, cria um plano de otimização digestiva e fornece orientações para melhorar sua qualidade de vida e prevenir que problemas se tornem mais severos.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Busque avaliação nutricional para uma análise personalizada que identifica padrões alimentares que causam desconforto. Uma nutricionista pode criar estratégias práticas para otimizar sua digestão, ajustar plano alimentar adequado e acompanhar sua evolução. Com pequenos ajustes personalizados, você pode melhorar significativamente sua saúde intestinal.',
      plano7Dias: '📅 PLANO 7 DIAS: Protocolo inicial com identificação de padrões alimentares problemáticos, estratégias práticas para otimizar digestão, plano alimentar adequado, cronograma de observação e ajustes, e acompanhamento para monitorar melhorias. O acompanhamento nutricional ajuda a identificar conexões sutis entre alimentação e sintomas.',
      suplementacao: '💊 SUPLEMENTAÇÃO: A necessidade só é definida após avaliação nutricional. Probióticos suaves, fibras de manutenção e enzimas digestivas leves podem ser considerados quando há indicação, mas sempre de acordo com a individualidade biológica e necessidades específicas identificadas na consulta.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um plano alimentar personalizado considera seus problemas moderados. Priorize alimentos que melhoram digestão, estratégias para identificar alimentos problemáticos e combinações que otimizam saúde intestinal. Uma nutricionista ajusta quantidades e combinações ideais para você, criando hábitos alimentares que promovem bem-estar contínuo.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Com um acompanhamento nutricional personalizado, você pode otimizar sua saúde intestinal e melhorar seu bem-estar. Agende uma avaliação nutricional para receber estratégias práticas adequadas ao seu perfil. Pequenos ajustes podem fazer grande diferença na sua qualidade de vida!'
    },
    saudeIntestinalAdequada: {
      diagnostico: '📋 DIAGNÓSTICO: Você parece ter uma boa saúde intestinal! Mesmo assim, um acompanhamento nutricional preventivo pode ajudar a manter esse equilíbrio e otimizar ainda mais seu bem-estar digestivo.',
      causaRaiz: '🔍 CAUSA RAIZ: Ter boa saúde intestinal é um grande ativo, mas mesmo pessoas com boa digestão podem se beneficiar de otimizações preventivas. Pesquisas mostram que hábitos alimentares inadequados ao longo do tempo podem levar ao desenvolvimento de problemas digestivos. Uma avaliação nutricional completa cria estratégias preventivas personalizadas e fornece orientações para manter seu bem-estar em longo prazo. A prevenção é sempre melhor que o tratamento.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Considere uma avaliação nutricional preventiva para otimizar sua saúde intestinal. Uma nutricionista pode criar estratégias personalizadas, ajustar plano alimentar adequado e fornecer orientações para manter sua excelente condição ao longo do tempo. A prevenção garante qualidade de vida contínua.',
      plano7Dias: '📅 PLANO 7 DIAS: Protocolo preventivo com otimização de saúde intestinal, estratégias para manter equilíbrio digestivo, plano alimentar adequado, orientações sobre combinações ideais de alimentos e acompanhamento para garantir que você mantenha sua excelente condição. A prevenção é a melhor estratégia.',
      suplementacao: '💊 SUPLEMENTAÇÃO: A necessidade só é definida após avaliação nutricional. Probióticos de manutenção e fibras preventivas podem ser considerados quando há indicação, mas sempre de acordo com a individualidade biológica e necessidades específicas identificadas na consulta.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um plano alimentar preventivo considera sua boa saúde intestinal atual. Priorize otimização nutricional, estratégias para manter excelente saúde intestinal e combinações alimentares ideais. Uma nutricionista ajusta quantidades e combinações para manter sua saúde intestinal em excelência.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Mantenha sua excelente saúde intestinal com estratégias preventivas personalizadas. Agende uma avaliação nutricional para receber orientações adequadas ao seu perfil. A prevenção é o melhor investimento para sua saúde a longo prazo!'
    }
  }
}

