/**
 * DIAGNÓSTICOS: Você está se Alimentando Conforme sua Rotina - ÁREA WELLNESS
 * 
 * Diagnósticos focados em adequação alimentar à rotina
 * que estimulam contato com especialista em bem-estar
 */

import { DiagnosticosPorFerramenta } from '../types'

export const alimentacaoRotinaDiagnosticos: DiagnosticosPorFerramenta = {
  wellness: {
    alimentacaoInadequada: {
      diagnostico: '⏰ DIAGNÓSTICO: Seu perfil indica que sua alimentação não está adequada à sua rotina. Um acompanhamento especializado é essencial para criar um plano alimentar personalizado que se adapte ao seu estilo de vida e otimize sua saúde.',
      causaRaiz: '🔍 CAUSA RAIZ: Alimentação inadequada à rotina pode levar a refeições irregulares, escolhas alimentares inadequadas por falta de tempo, pular refeições, comer em horários inadequados e não adequar nutrição ao estilo de vida. Pesquisas mostram que até 80% das pessoas não adequam alimentação à rotina, o que pode levar a problemas de saúde e bem-estar. Quando não identificado e tratado, esse padrão pode piorar ao longo do tempo. Um especialista em bem-estar experiente pode ajudar a entender sua rotina específica, criar um plano alimentar personalizado que se adapta ao seu estilo de vida, recomendar produtos práticos e adequados à rotina (como shakes práticos, produtos para refeições rápidas, produtos adaptados a diferentes horários) e fornecer acompanhamento constante. A combinação de produtos adequados com estratégias nutricionais personalizadas faz toda diferença na adequação alimentar à rotina.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Busque um acompanhamento especializado urgente com um especialista em bem-estar para adequar sua alimentação à sua rotina. Um profissional experiente pode criar um plano personalizado que inclui produtos práticos e adequados à rotina, estratégias nutricionais otimizadas que se adaptam ao seu estilo de vida, receitas práticas e rápidas, protocolos de suplementação adequados e acompanhamento constante. Produtos de qualidade como shakes práticos e produtos para refeições rápidas podem ser fundamentais para sua jornada de alimentação adequada à rotina.',
      plano7Dias: '📅 PLANO 7 DIAS: Conecte-se com um especialista em bem-estar para receber um plano personalizado que inclui: produtos práticos e adequados à rotina, estratégias nutricionais otimizadas que se adaptam ao seu estilo de vida, cronograma detalhado de uso dos produtos adaptado à sua rotina, acompanhamento diário para monitorar adequação, ajustes conforme sua resposta individual e suporte constante. O suporte profissional é fundamental para uma adequação alimentar segura e eficaz.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Um especialista em bem-estar pode recomendar produtos específicos que se adaptam à sua rotina, como shakes práticos para diferentes momentos do dia, produtos para refeições rápidas, suplementos adaptados a horários específicos, produtos para energia ao longo do dia e protocolos personalizados de suplementação. O acompanhamento profissional garante que você use os produtos certos nos momentos adequados, potencializando resultados e garantindo alimentação adequada à rotina.',
      alimentacao: '🍎 ALIMENTAÇÃO: Com o acompanhamento de um especialista em bem-estar, você receberá orientações personalizadas sobre como adequar alimentação à sua rotina, receitas práticas e rápidas adaptadas ao seu estilo de vida, estratégias de timing alimentar para diferentes momentos do dia, dicas para manter alimentação adequada mesmo com rotina corrida e suporte constante para criar hábitos alimentares que se adaptam à rotina. O mentor te ajuda a entender como adequar cada refeição ao seu estilo de vida.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Sua saúde pode melhorar significativamente ao adequar alimentação à sua rotina. Entre em contato com um especialista em bem-estar para receber um acompanhamento especializado urgente que vai desde produtos práticos e adequados à rotina até estratégias personalizadas de alimentação adaptada. Você não precisa conviver com alimentação inadequada à rotina — um profissional pode te ajudar a encontrar soluções que transformam seu bem-estar. Sua jornada para alimentação adequada à rotina começa agora!'
    },
    alimentacaoParcialmenteAdequada: {
      diagnostico: '⏰ DIAGNÓSTICO: Você está parcialmente se alimentando conforme sua rotina, mas pode ser otimizado. Um acompanhamento pode ajudar a criar estratégias mais adequadas ao seu estilo de vida.',
      causaRaiz: '🔍 CAUSA RAIZ: Alimentação parcialmente adequada indica boa base, mas há oportunidades de otimização para melhor adequação à rotina. Pesquisas indicam que muitas pessoas têm alguma adequação mas podem melhorar ainda mais. Um especialista em bem-estar pode ajudar a identificar oportunidades específicas de otimização, criar estratégias personalizadas e recomendar produtos que se adaptam melhor à rotina, elevando seus resultados para o próximo nível.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Conecte-se com um especialista em bem-estar para receber estratégias de otimização alimentar personalizadas para sua rotina. Um profissional pode criar um plano que inclui produtos que se adaptam melhor à rotina, estratégias nutricionais otimizadas, ajustes no estilo de vida e acompanhamento para garantir que você alcance máxima adequação alimentar. Com pequenos ajustes personalizados, você pode melhorar significativamente sua alimentação.',
      plano7Dias: '📅 PLANO 7 DIAS: Um especialista em bem-estar pode criar um plano de otimização alimentar que inclui: produtos que se adaptam melhor à rotina, estratégias nutricionais otimizadas, ajustes no timing das refeições, protocolo de suplementação adequado, acompanhamento para monitorar melhorias e ajustes conforme seu progresso individual. O acompanhamento regular garante otimização contínua.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Com base no seu perfil, um especialista em bem-estar pode recomendar produtos que otimizam sua alimentação para rotina, como shakes práticos otimizados, suplementos de manutenção adaptados, produtos para energia e protocolos personalizados. O acompanhamento profissional garante escolhas adequadas e maximiza adequação.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um especialista em bem-estar pode fornecer orientações sobre otimização nutricional para rotina, estratégias de timing alimentar otimizadas, combinações de alimentos práticas, receitas rápidas e suporte para criar hábitos que mantêm alimentação otimizada para rotina. O acompanhamento ajuda a transformar conhecimento em ação prática.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Com estratégias personalizadas, você pode otimizar sua alimentação para rotina e melhorar seus resultados. Entre em contato com um especialista em bem-estar para receber um plano de otimização alimentar. Produtos adequados e estratégias personalizadas podem fazer toda diferença na sua adequação alimentar!'
    },
    alimentacaoAdequada: {
      diagnostico: '⏰ DIAGNÓSTICO: Você já está se alimentando bem conforme sua rotina! Mesmo assim, um acompanhamento preventivo pode ajudar a manter essa adequação e otimizar ainda mais sua alimentação.',
      causaRaiz: '🔍 CAUSA RAIZ: Ter alimentação adequada à rotina é um grande ativo, mas pode ser otimizado ainda mais com estratégias preventivas e produtos adequados. Pesquisas mostram que adequação alimentar pode ser mantida e otimizada continuamente. Um especialista em bem-estar pode criar estratégias preventivas personalizadas, recomendar produtos que mantêm adequação alimentar e fornecer orientações para manter seu bem-estar em longo prazo. A prevenção é sempre melhor que o tratamento.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Considere um acompanhamento preventivo com um especialista em bem-estar para otimizar sua alimentação. Um profissional pode criar estratégias personalizadas, recomendar produtos que mantêm adequação alimentar e fornecer orientações para manter sua excelente condição ao longo do tempo. A prevenção garante qualidade de vida contínua.',
      plano7Dias: '📅 PLANO 7 DIAS: Um especialista em bem-estar pode criar um plano preventivo personalizado que inclui: otimização de alimentação para rotina, estratégias para manter adequação alimentar, produtos preventivos que mantêm adequação, orientações sobre combinações ideais de alimentos e acompanhamento para garantir que você mantenha sua excelente condição. A prevenção é a melhor estratégia.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Com base no seu perfil, um especialista em bem-estar pode recomendar produtos preventivos que mantêm sua adequação alimentar, como shakes de manutenção, suplementos preventivos adaptados, produtos para nutrição otimizada e protocolos personalizados. A suplementação preventiva mantém sua excelente saúde.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um especialista em bem-estar pode fornecer orientações sobre otimização nutricional preventiva, estratégias para manter excelente adequação alimentar, receitas que potencializam bem-estar, dicas sobre combinações alimentares ideais e suporte para criar hábitos que mantêm sua alimentação adequada em excelência. A prevenção garante qualidade de vida contínua.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Mantenha sua excelente alimentação adequada à rotina com estratégias preventivas personalizadas. Entre em contato com um especialista em bem-estar para receber orientações e produtos que mantêm seu bem-estar. A prevenção é o melhor investimento para sua saúde a longo prazo!'
    }
  }
}

