/**
 * DIAGNÓSTICOS: Quiz Alimentação Saudável - ÁREA WELLNESS
 * 
 * Diagnósticos focados em identificar qualidade da alimentação
 * que estimulam contato com distribuidor Herbalife
 */

import { DiagnosticosPorFerramenta } from '../types'

export const alimentacaoSaudavelDiagnosticos: DiagnosticosPorFerramenta = {
  wellness: {
    alimentacaoPrecisaMelhorar: {
      diagnostico: '🥗 DIAGNÓSTICO: Seu perfil indica que sua alimentação precisa de melhorias significativas. Um acompanhamento especializado é essencial para transformar seus hábitos alimentares e melhorar significativamente sua saúde e bem-estar.',
      causaRaiz: '🔍 CAUSA RAIZ: Alimentação inadequada pode impactar negativamente energia, peso, saúde digestiva, imunidade e qualidade de vida. Pesquisas mostram que até 70% das pessoas não consomem nutrientes adequados diariamente, o que pode levar a problemas de saúde a longo prazo. Quando não identificados e tratados, hábitos alimentares inadequados podem piorar ao longo do tempo. Um distribuidor Herbalife experiente pode ajudar a identificar padrões alimentares problemáticos, criar um plano alimentar saudável personalizado, recomendar produtos de qualidade que complementam alimentação (como shakes nutritivos, suplementos e produtos de apoio) e fornecer acompanhamento constante. A combinação de produtos adequados com estratégias nutricionais personalizadas faz toda diferença na transformação alimentar.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Busque um acompanhamento especializado com um distribuidor Herbalife para transformar sua alimentação. Um profissional experiente pode criar um plano personalizado que inclui produtos de qualidade que complementam alimentação, estratégias nutricionais otimizadas, receitas práticas e deliciosas, protocolos de suplementação adequados e acompanhamento constante. Produtos Herbalife como shakes nutritivos e suplementos podem ser fundamentais para sua jornada de alimentação saudável.',
      plano7Dias: '📅 PLANO 7 DIAS: Conecte-se com um distribuidor Herbalife para receber um plano personalizado que inclui: produtos de qualidade que complementam alimentação, estratégias nutricionais otimizadas para criar hábitos saudáveis, cronograma detalhado de uso dos produtos, acompanhamento diário para monitorar progresso, ajustes conforme sua resposta individual e suporte constante. O suporte profissional é fundamental para uma transformação alimentar segura e eficaz.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Um distribuidor Herbalife pode recomendar produtos específicos que complementam alimentação saudável, como shakes nutritivos de alta qualidade, suplementos que garantem nutrição adequada, produtos para energia e bem-estar, multivitamínicos para completar nutrição e protocolos personalizados de suplementação. O acompanhamento profissional garante que você use os produtos certos nas doses adequadas, potencializando resultados e garantindo nutrição completa.',
      alimentacao: '🍎 ALIMENTAÇÃO: Com o acompanhamento de um distribuidor Herbalife, você receberá orientações personalizadas sobre alimentação saudável, receitas práticas e deliciosas adaptadas ao seu estilo de vida, estratégias de combinação de alimentos para maximizar nutrição, dicas para criar hábitos alimentares saudáveis e suporte constante para transformar sua relação com comida. O mentor te ajuda a entender como cada alimento impacta sua saúde.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Sua saúde pode melhorar significativamente ao transformar sua alimentação. Entre em contato com um distribuidor Herbalife para receber um acompanhamento especializado que vai desde produtos de qualidade que complementam alimentação até estratégias personalizadas de nutrição. Você não precisa conviver com alimentação inadequada — um profissional pode te ajudar a encontrar soluções que transformam seu bem-estar. Sua jornada para alimentação saudável começa agora!'
    },
    alimentacaoModerada: {
      diagnostico: '🥗 DIAGNÓSTICO: Você tem uma base alimentar, mas pode ser otimizada. Um acompanhamento pode ajudar a melhorar seus hábitos e criar uma alimentação mais saudável e equilibrada.',
      causaRaiz: '🔍 CAUSA RAIZ: Alimentação moderada indica boa base, mas há oportunidades de otimização. Pesquisas indicam que muitas pessoas têm padrões alimentares que podem ser melhorados para maximizar saúde e bem-estar. Um distribuidor Herbalife pode ajudar a identificar oportunidades específicas de otimização, criar estratégias personalizadas e recomendar produtos que complementam alimentação, elevando seus resultados para o próximo nível.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Conecte-se com um distribuidor Herbalife para receber estratégias de otimização alimentar personalizadas. Um profissional pode criar um plano que inclui produtos que complementam alimentação, estratégias nutricionais otimizadas, ajustes no estilo de vida e acompanhamento para garantir que você alcance máxima qualidade alimentar. Com pequenos ajustes personalizados, você pode melhorar significativamente seus hábitos alimentares.',
      plano7Dias: '📅 PLANO 7 DIAS: Um distribuidor Herbalife pode criar um plano de otimização alimentar que inclui: produtos que complementam alimentação, estratégias nutricionais otimizadas, ajustes no timing das refeições, protocolo de suplementação adequado, acompanhamento para monitorar melhorias e ajustes conforme seu progresso individual. O acompanhamento regular garante otimização contínua.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Com base no seu perfil, um distribuidor Herbalife pode recomendar produtos que otimizam sua alimentação, como shakes nutritivos, suplementos de manutenção, produtos para energia e protocolos personalizados. O acompanhamento profissional garante escolhas adequadas e maximiza resultados.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um distribuidor Herbalife pode fornecer orientações sobre otimização nutricional, estratégias de timing alimentar, combinações de alimentos que maximizam nutrição, receitas práticas e suporte para criar hábitos que mantêm alimentação otimizada. O acompanhamento ajuda a transformar conhecimento em ação prática.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Com estratégias personalizadas, você pode otimizar sua alimentação e melhorar seus resultados. Entre em contato com um distribuidor Herbalife para receber um plano de otimização alimentar. Produtos adequados e estratégias personalizadas podem fazer toda diferença na sua qualidade alimentar!'
    },
    alimentacaoSaudavel: {
      diagnostico: '🥗 DIAGNÓSTICO: Você já tem bons hábitos alimentares! Mesmo assim, um acompanhamento preventivo pode ajudar a manter essa qualidade e otimizar ainda mais sua alimentação.',
      causaRaiz: '🔍 CAUSA RAIZ: Ter bons hábitos alimentares é um grande ativo, mas pode ser otimizado ainda mais com estratégias preventivas e produtos adequados. Pesquisas mostram que hábitos alimentares inadequados ao longo do tempo podem levar ao declínio da qualidade alimentar. Um distribuidor Herbalife pode criar estratégias preventivas personalizadas, recomendar produtos que mantêm qualidade alimentar e fornecer orientações para manter seu bem-estar em longo prazo. A prevenção é sempre melhor que o tratamento.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Considere um acompanhamento preventivo com um distribuidor Herbalife para otimizar sua alimentação. Um profissional pode criar estratégias personalizadas, recomendar produtos que mantêm qualidade alimentar e fornecer orientações para manter sua excelente condição ao longo do tempo. A prevenção garante qualidade de vida contínua.',
      plano7Dias: '📅 PLANO 7 DIAS: Um distribuidor Herbalife pode criar um plano preventivo personalizado que inclui: otimização de alimentação, estratégias para manter qualidade alimentar, produtos preventivos que mantêm nutrição, orientações sobre combinações ideais de alimentos e acompanhamento para garantir que você mantenha sua excelente condição. A prevenção é a melhor estratégia.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Com base no seu perfil, um distribuidor Herbalife pode recomendar produtos preventivos que mantêm sua qualidade alimentar, como shakes de manutenção, suplementos preventivos, produtos para nutrição otimizada e protocolos personalizados. A suplementação preventiva mantém sua excelente saúde.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um distribuidor Herbalife pode fornecer orientações sobre otimização nutricional preventiva, estratégias para manter excelente qualidade alimentar, receitas que potencializam bem-estar, dicas sobre combinações alimentares ideais e suporte para criar hábitos que mantêm sua alimentação saudável em excelência. A prevenção garante qualidade de vida contínua.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Mantenha sua excelente alimentação com estratégias preventivas personalizadas. Entre em contato com um distribuidor Herbalife para receber orientações e produtos que mantêm seu bem-estar. A prevenção é o melhor investimento para sua saúde a longo prazo!'
    }
  }
}

