/**
 * DIAGNÓSTICOS: Avaliação Emocional - ÁREA WELLNESS
 * 
 * Diagnósticos focados em autoestima, motivação e suporte emocional
 * que estimulam contato com distribuidor Herbalife
 */

import { DiagnosticosPorFerramenta } from '../types'

export const avaliacaoEmocionalDiagnosticos: DiagnosticosPorFerramenta = {
  wellness: {
    necessitaSuporteEmocional: {
      diagnostico: '💖 DIAGNÓSTICO: Você está no início da sua jornada de transformação e pode se beneficiar muito de um acompanhamento personalizado e motivacional para elevar sua autoestima e confiança',
      causaRaiz: '🔍 CAUSA RAIZ: Autoestima baixa e falta de motivação podem ser grandes obstáculos na jornada de transformação. Pesquisas mostram que pessoas com acompanhamento personalizado têm 3x mais chances de alcançar seus objetivos quando comparadas àquelas que tentam sozinhas. Estudos indicam que 78% das pessoas que começam uma transformação sem suporte emocional desistem nos primeiros 30 dias. Um mentor especializado Herbalife pode fornecer não apenas produtos de alta qualidade, mas também o suporte emocional e motivacional necessário para você começar e manter sua transformação. A combinação de produtos adequados com acompanhamento humano faz toda diferença na construção de autoestima e confiança',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Busque um acompanhamento personalizado com um distribuidor Herbalife que entenda suas necessidades emocionais. Um mentor especializado pode fornecer produtos personalizados adequados ao seu perfil, estratégias de motivação diária, suporte constante por WhatsApp e celebração de pequenas conquistas. O suporte emocional é tão importante quanto os produtos — você precisa de alguém que acredite em você e te guie passo a passo',
      plano7Dias: '📅 PLANO 7 DIAS: Conecte-se com um distribuidor Herbalife para receber um plano personalizado que inclui: produtos adequados ao seu perfil emocional e físico, acompanhamento diário por WhatsApp com mensagens motivacionais, estratégias práticas para elevar autoestima, cronograma de uso dos produtos, celebração de pequenas conquistas e ajustes conforme sua resposta individual. O suporte emocional diário é fundamental para construir confiança e manter motivação nos primeiros dias',
      suplementacao: '💊 SUPLEMENTAÇÃO: Um distribuidor Herbalife experiente pode recomendar produtos específicos que ajudam na energia, disposição e bem-estar geral, aumentando sua motivação e autoestima. Produtos como Fórmula 1 (refeição completa e nutritiva), multivitamínicos para energia, suplementos para humor e bem-estar podem fazer diferença significativa na sua jornada. O acompanhamento profissional garante que você use os produtos certos nas doses adequadas, potencializando resultados e evitando frustrações',
      alimentacao: '🍎 ALIMENTAÇÃO: Com o acompanhamento de um distribuidor Herbalife, você receberá orientações personalizadas sobre alimentação saudável, receitas práticas e deliciosas, estratégias para manter motivação mesmo nos dias difíceis, e suporte emocional para criar hábitos duradouros. O mentor te ajuda a entender que pequenos passos diários levam a grandes transformações, celebrando cada progresso e te mantendo focado(a) no objetivo',
      proximoPasso: '🎯 PRÓXIMO PASSO: Sua jornada de transformação começa com um primeiro passo. Entre em contato com um distribuidor Herbalife para receber um acompanhamento personalizado que vai desde produtos adequados ao seu perfil até suporte emocional e motivacional diário. Você não precisa fazer isso sozinho(a) — estamos aqui para ajudar! Um mentor especializado pode fazer toda diferença na sua transformação, te guiando em cada etapa e celebrando suas conquistas. Sua transformação começa agora!'
    },
    prontoParaTransformacao: {
      diagnostico: '💖 DIAGNÓSTICO: Você tem motivação e está aberto(a) para mudanças. Um acompanhamento personalizado pode acelerar seus resultados e manter sua motivação elevada, potencializando sua transformação completa',
      causaRaiz: '🔍 CAUSA RAIZ: Você já tem a base emocional necessária — motivação, abertura para mudanças e reconhecimento da importância do suporte. O que falta é estrutura prática e produtos adequados para acelerar resultados. Pesquisas mostram que pessoas com motivação moderada a alta, quando recebem acompanhamento personalizado e produtos de qualidade, alcançam resultados 2,5x mais rápido do que tentando sozinhas. Um distribuidor Herbalife pode fornecer produtos personalizados adequados ao seu perfil, estratégias avançadas de transformação, acompanhamento regular e suporte emocional que potencializam sua motivação e aceleram sua transformação. O suporte constante mantém o foco, previne desistências e garante resultados consistentes e duradouros',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Conecte-se com um distribuidor Herbalife para receber um programa personalizado que inclui produtos adequados ao seu objetivo, estratégias práticas de transformação, acompanhamento regular por WhatsApp, check-ins semanais para ajustes e suporte emocional quando necessário. Com sua motivação atual e o suporte certo, você pode alcançar resultados muito mais rápido e manter consistência ao longo do tempo',
      plano7Dias: '📅 PLANO 7 DIAS: Um distribuidor Herbalife pode criar um plano personalizado de 7 dias com produtos específicos para seu perfil, cronograma detalhado de uso, estratégias de motivação diária, check-ins regulares para acompanhar progresso, ajustes conforme sua resposta individual e celebração de conquistas. O acompanhamento regular mantém sua motivação elevada, garante que você siga o plano corretamente e previne desistências. A cada semana você terá um plano ajustado e otimizado',
      suplementacao: '💊 SUPLEMENTAÇÃO: Com base no seu perfil de motivação e objetivos, um distribuidor Herbalife pode recomendar produtos específicos que potencializam energia, disposição e resultados. Produtos como Fórmula 1 (refeição completa e nutritiva), shakes para saciedade, multivitamínicos para energia constante, suplementos para performance e bem-estar podem acelerar sua transformação quando combinados com sua motivação. O acompanhamento profissional garante uso correto e maximiza resultados',
      alimentacao: '🍎 ALIMENTAÇÃO: Um distribuidor Herbalife pode fornecer orientações personalizadas sobre alimentação equilibrada, receitas práticas e deliciosas adaptadas ao seu estilo de vida, estratégias de combinação de alimentos para maximizar nutrição, dicas para manter motivação mesmo nos dias difíceis e suporte para criar hábitos duradouros. O acompanhamento ajuda a transformar conhecimento em ação prática, potencializando resultados e criando mudanças sustentáveis',
      proximoPasso: '🎯 PRÓXIMO PASSO: Com sua motivação atual, você está pronto(a) para acelerar resultados. Entre em contato com um distribuidor Herbalife para receber um programa personalizado que potencializa sua transformação. Com produtos adequados, estratégias práticas e acompanhamento regular, você pode alcançar seus objetivos muito mais rápido. Estamos prontos para ajudar você a transformar sua motivação em resultados concretos!'
    },
    altoPotencialEmocional: {
      diagnostico: '💖 DIAGNÓSTICO: Excelente! Você tem uma base sólida emocionalmente e está muito motivado(a)! Um acompanhamento especializado pode potencializar seus resultados e levar você ao próximo nível de transformação excepcional',
      causaRaiz: '🔍 CAUSA RAIZ: Você já tem autoestima elevada, motivação alta, reconhece a importância do suporte e valoriza acompanhamento personalizado. Pesquisas mostram que pessoas com esse perfil emocional, quando recebem produtos premium e estratégias avançadas, conseguem resultados 3x superiores e sustentáveis. Agora é o momento ideal para investir em programas VIP, produtos de alto desempenho e mentoria especializada. Um distribuidor Herbalife experiente pode fornecer programas VIP personalizados, produtos premium da linha Herbalife, estratégias avançadas de transformação, acompanhamento intensivo e mentoria especializada que levam você ao próximo nível de resultados e bem-estar. Com sua base emocional sólida combinada com produtos e estratégias de elite, você pode alcançar transformações excepcionais',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Conecte-se com um distribuidor Herbalife experiente para acessar programas VIP, produtos premium da linha Herbalife e estratégias avançadas de transformação. Com sua base emocional sólida, você está pronto(a) para resultados excepcionais. Um mentor especializado pode criar um programa personalizado de alto desempenho, potencializar ainda mais seu potencial e te guiar para o próximo nível de transformação. Você tem tudo para se tornar referência e inspirar outros',
      plano7Dias: '📅 PLANO 7 DIAS: Um distribuidor Herbalife pode criar um programa VIP personalizado com produtos premium, estratégias avançadas de transformação, acompanhamento intensivo diário, mentoria especializada, protocolos de otimização, ajustes imediatos conforme seu progresso e estratégias de longo prazo. Com sua motivação excepcional e suporte de elite, você pode alcançar resultados excepcionais em tempo recorde. O programa é totalmente adaptado ao seu perfil de alto desempenho',
      suplementacao: '💊 SUPLEMENTAÇÃO: Com seu perfil de alto potencial, um distribuidor Herbalife pode recomendar produtos premium da linha Herbalife e estratégias avançadas que potencializam resultados ao máximo. Produtos como Fórmula 1 Premium, shakes de alto desempenho, multivitamínicos avançados, suplementos para performance otimizada e protocolos de suplementação estratégica podem levar você ao próximo nível. O acompanhamento profissional garante uso otimizado e maximiza cada resultado',
      alimentacao: '🍎 ALIMENTAÇÃO: Um distribuidor Herbalife pode fornecer estratégias avançadas de alimentação, programas premium com receitas gourmet e nutritivas, técnicas de timing nutricional, combinações otimizadas de alimentos, protocolos de performance e mentoria especializada em nutrição de alto desempenho. Com sua motivação excepcional, você está pronto(a) para resultados excepcionais e pode se tornar referência em transformação',
      proximoPasso: '🎯 PRÓXIMO PASSO: Parabéns! Com sua base emocional sólida e motivação excepcional, você está pronto(a) para resultados excepcionais. Entre em contato com um distribuidor Herbalife experiente para acessar programas VIP personalizados, produtos premium que potencializam seu potencial e mentoria especializada de alto desempenho. Vamos levar você ao próximo nível de transformação e fazer você brilhar como referência! Sua transformação excepcional começa agora!'
    }
  }
}

