/**
 * DIAGNÓSTICOS: Você Conhece o Seu Corpo - ÁREA WELLNESS
 * 
 * Diagnósticos focados em autoconhecimento corporal
 * que estimulam contato com distribuidor Herbalife
 */

import { DiagnosticosPorFerramenta } from '../types'

export const conheceSeuCorpoDiagnosticos: DiagnosticosPorFerramenta = {
  wellness: {
    conhecimentoBaixo: {
      diagnostico: '🧠 DIAGNÓSTICO: Seu perfil indica que você precisa conhecer melhor seu corpo. Um acompanhamento especializado pode ajudar a entender seus sinais, identificar necessidades e criar estratégias personalizadas para melhorar seu bem-estar e autoconhecimento corporal.',
      causaRaiz: '🔍 CAUSA RAIZ: Falta de autoconhecimento corporal pode levar a ignorar sinais importantes do corpo, não identificar necessidades nutricionais específicas, não reconhecer padrões de fome e saciedade, e não entender como diferentes alimentos e produtos afetam seu organismo. Pesquisas mostram que até 70% das pessoas não conhecem adequadamente seus próprios sinais corporais. Quando não desenvolvido, o autoconhecimento pode piorar ao longo do tempo. Um distribuidor Herbalife experiente pode ajudar a desenvolver autoconhecimento corporal, criar estratégias personalizadas de observação, recomendar produtos e protocolos que facilitam autoconhecimento (como diários alimentares, produtos de apoio, protocolos de observação) e fornecer acompanhamento constante. A combinação de produtos adequados com estratégias de autoconhecimento personalizadas faz toda diferença na transformação do relacionamento com o corpo.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Busque um acompanhamento especializado com um distribuidor Herbalife para desenvolver autoconhecimento corporal. Um profissional experiente pode criar um plano personalizado que inclui estratégias de observação, produtos que facilitam autoconhecimento, protocolos de atenção aos sinais corporais, diários e ferramentas de registro e acompanhamento constante. Produtos Herbalife como protocolos de observação e ferramentas de registro pode ser fundamental para sua jornada de autoconhecimento.',
      plano7Dias: '📅 PLANO 7 DIAS: Conecte-se com um distribuidor Herbalife para receber um plano personalizado que inclui: estratégias de observação corporal, produtos que facilitam autoconhecimento, protocolos de atenção aos sinais (fome, saciedade, energia), cronograma detalhado de observação e registro, acompanhamento diário para monitorar progresso e ajustes conforme sua resposta individual. O suporte profissional é fundamental para um desenvolvimento de autoconhecimento eficaz.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Um distribuidor Herbalife pode recomendar produtos específicos que facilitam autoconhecimento corporal, como protocolos de observação para diferentes produtos, ferramentas de registro e acompanhamento, produtos de apoio que ajudam a identificar respostas corporais e protocolos personalizados de experimentação. O acompanhamento profissional garante que você desenvolva autoconhecimento de forma estruturada e eficaz.',
      alimentacao: '🍎 ALIMENTAÇÃO: Com o acompanhamento de um distribuidor Herbalife, você receberá orientações personalizadas sobre como observar sinais corporais relacionados à alimentação, estratégias para identificar padrões de fome e saciedade, aprendizado sobre como diferentes alimentos afetam seu corpo, técnicas de atenção plena na alimentação e suporte constante para desenvolver autoconhecimento alimentar. O mentor te ajuda a entender como cada alimento impacta seu corpo de forma única.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Seu bem-estar pode melhorar significativamente ao conhecer melhor seu corpo. Entre em contato com um distribuidor Herbalife para receber um acompanhamento especializado que vai desde estratégias de autoconhecimento até produtos e protocolos que facilitam a observação corporal. Você não precisa conviver com falta de autoconhecimento — um profissional pode te ajudar a desenvolver uma relação mais profunda com seu corpo. Sua jornada para autoconhecimento corporal começa agora!'
    },
    conhecimentoModerado: {
      diagnostico: '🧠 DIAGNÓSTICO: Você tem uma base de conhecimento sobre seu corpo, mas pode ser aprofundado. Um acompanhamento pode ajudar a entender melhor seus sinais e criar estratégias mais personalizadas para seu bem-estar.',
      causaRaiz: '🔍 CAUSA RAIZ: Conhecimento moderado indica boa base, mas há oportunidades de aprofundamento. Pesquisas indicam que muitas pessoas têm conhecimento básico que pode ser expandido para melhorar resultados. Um distribuidor Herbalife pode ajudar a identificar oportunidades específicas de aprofundamento, criar estratégias avançadas de autoconhecimento e recomendar produtos que facilitam observação mais profunda, elevando seus resultados para o próximo nível.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Conecte-se com um distribuidor Herbalife para receber estratégias avançadas de autoconhecimento corporal personalizadas. Um profissional pode criar um plano que inclui técnicas avançadas de observação, produtos que facilitam autoconhecimento profundo, ajustes no estilo de vida e acompanhamento para garantir que você desenvolva conhecimento mais profundo sobre seu corpo. Com pequenos ajustes personalizados, você pode melhorar significativamente seu autoconhecimento.',
      plano7Dias: '📅 PLANO 7 DIAS: Um distribuidor Herbalife pode criar um plano de aprofundamento que inclui: estratégias avançadas de observação corporal, produtos que facilitam autoconhecimento profundo, técnicas de atenção plena, protocolo de registro detalhado, acompanhamento para monitorar desenvolvimento e ajustes conforme seu progresso individual. O acompanhamento regular garante aprofundamento contínuo.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Com base no seu perfil, um distribuidor Herbalife pode recomendar produtos que aprofundam autoconhecimento, como protocolos avançados de observação, ferramentas de registro detalhadas, produtos de apoio para experimentação e protocolos personalizados. O acompanhamento profissional garante escolhas adequadas e maximiza desenvolvimento de autoconhecimento.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um distribuidor Herbalife pode fornecer orientações sobre técnicas avançadas de observação alimentar, estratégias para identificar padrões sutis, aprendizado sobre respostas corporais específicas, técnicas de atenção plena na alimentação e suporte para criar hábitos que mantêm autoconhecimento aprofundado. O acompanhamento ajuda a transformar conhecimento em ação prática avançada.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Com estratégias personalizadas avançadas, você pode aprofundar seu conhecimento sobre seu corpo e melhorar seus resultados. Entre em contato com um distribuidor Herbalife para receber um plano de aprofundamento de autoconhecimento. Produtos adequados e estratégias avançadas podem fazer toda diferença na sua qualidade de conhecimento corporal!'
    },
    conhecimentoAlto: {
      diagnostico: '🧠 DIAGNÓSTICO: Você já conhece bem seu corpo! Mesmo assim, um acompanhamento preventivo pode ajudar a manter esse conhecimento atualizado e otimizar ainda mais seu autoconhecimento corporal.',
      causaRaiz: '🔍 CAUSA RAIZ: Ter bom conhecimento corporal é um grande ativo, mas pode ser otimizado ainda mais com estratégias preventivas e produtos adequados. Pesquisas mostram que conhecimento corporal pode evoluir continuamente com novas técnicas e observações. Um distribuidor Herbalife pode criar estratégias preventivas personalizadas, recomendar produtos que mantêm e otimizam autoconhecimento e fornecer orientações para manter seu bem-estar em longo prazo. A prevenção e otimização são sempre melhores que o tratamento.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Considere um acompanhamento preventivo com um distribuidor Herbalife para otimizar seu conhecimento corporal. Um profissional pode criar estratégias personalizadas, recomendar produtos que mantêm autoconhecimento otimizado e fornecer orientações para manter sua excelente condição ao longo do tempo. A prevenção garante qualidade de vida contínua.',
      plano7Dias: '📅 PLANO 7 DIAS: Um distribuidor Herbalife pode criar um plano preventivo personalizado que inclui: otimização de autoconhecimento corporal, estratégias para manter conhecimento atualizado, produtos preventivos que mantêm observação, orientações sobre técnicas avançadas de observação e acompanhamento para garantir que você mantenha sua excelente condição. A prevenção é a melhor estratégia.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Com base no seu perfil, um distribuidor Herbalife pode recomendar produtos preventivos que mantêm seu conhecimento corporal, como protocolos de manutenção de observação, produtos que facilitam autoconhecimento contínuo, ferramentas de registro e protocolos personalizados. A suplementação e estratégias preventivas mantêm sua excelente autoconhecimento.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um distribuidor Herbalife pode fornecer orientações sobre otimização nutricional preventiva, estratégias para manter excelente conhecimento alimentar, técnicas avançadas de observação, dicas sobre manutenção de autoconhecimento e suporte para criar hábitos que mantêm seu conhecimento corporal em excelência. A prevenção garante qualidade de vida contínua.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Mantenha seu excelente conhecimento corporal com estratégias preventivas personalizadas. Entre em contato com um distribuidor Herbalife para receber orientações e produtos que mantêm seu autoconhecimento. A prevenção é o melhor investimento para sua saúde a longo prazo!'
    }
  }
}

