/**
 * DIAGNÓSTICOS: Diagnóstico de Eletrólitos - ÁREA WELLNESS
 * 
 * Diagnósticos focados em identificar desequilíbrios eletrolíticos
 * que estimulam contato com distribuidor Herbalife
 */

import { DiagnosticosPorFerramenta } from '../types'

export const eletrolitosDiagnosticos: DiagnosticosPorFerramenta = {
  wellness: {
    desequilibrioEletrolitico: {
      diagnostico: '⚡ DIAGNÓSTICO: Seus sintomas indicam possível desequilíbrio eletrolítico. Um acompanhamento especializado é essencial para identificar e corrigir esse desequilíbrio, melhorando significativamente seu bem-estar e energia.',
      causaRaiz: '🔍 CAUSA RAIZ: Desequilíbrios eletrolíticos podem causar cãibras musculares, fadiga, fraqueza, tonturas e até mesmo problemas de concentração. Pesquisas mostram que até 75% das pessoas não ingerem eletrólitos suficientes diariamente, mesmo consumindo água adequada. Quando não identificados e tratados, esses desequilíbrios podem impactar negativamente a qualidade de vida, performance física e bem-estar geral. Um distribuidor Herbalife experiente pode ajudar a identificar padrões de desequilíbrio, criar um plano personalizado de hidratação e eletrólitos, e recomendar produtos específicos que ajudam a manter o equilíbrio adequado. A combinação de hidratação adequada com eletrólitos equilibrados faz toda diferença na energia e bem-estar.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Busque um acompanhamento especializado com um distribuidor Herbalife para identificar e corrigir seu desequilíbrio eletrolítico. Um profissional experiente pode criar um plano personalizado que inclui produtos específicos para equilíbrio eletrolítico, estratégias de hidratação otimizada, cronograma de uso e acompanhamento constante. Produtos Herbalife como bebidas eletrolíticas e suplementos específicos podem ser fundamentais para restaurar seu equilíbrio de forma segura e eficaz.',
      plano7Dias: '📅 PLANO 7 DIAS: Conecte-se com um distribuidor Herbalife para receber um plano personalizado que inclui: produtos específicos para equilíbrio eletrolítico, estratégias de hidratação otimizada, cronograma detalhado de uso dos produtos, acompanhamento diário para monitorar melhorias, ajustes conforme sua resposta individual e suporte constante. O suporte profissional é fundamental para uma correção segura e eficaz do desequilíbrio.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Um distribuidor Herbalife pode recomendar produtos específicos que ajudam a manter o equilíbrio eletrolítico, como bebidas eletrolíticas, suplementos de magnésio e potássio, produtos para hidratação otimizada e protocolos personalizados de reposição eletrolítica. O acompanhamento profissional garante que você use os produtos certos nas doses adequadas, potencializando resultados e evitando excessos.',
      alimentacao: '🍎 ALIMENTAÇÃO: Com o acompanhamento de um distribuidor Herbalife, você receberá orientações personalizadas sobre alimentação rica em eletrólitos, estratégias de hidratação combinada com nutrição, receitas práticas e deliciosas, e suporte constante para criar hábitos que mantêm equilíbrio eletrolítico adequado. O mentor te ajuda a entender como cada alimento e bebida impacta seu equilíbrio.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Seu bem-estar pode melhorar significativamente ao corrigir o desequilíbrio eletrolítico. Entre em contato com um distribuidor Herbalife para receber um acompanhamento especializado que vai desde produtos específicos para equilíbrio até estratégias personalizadas de hidratação. Você não precisa conviver com sintomas de desequilíbrio — um profissional pode te ajudar a encontrar soluções que transformam seu bem-estar. Sua jornada para equilíbrio eletrolítico começa agora!'
    },
    desequilibrioModerado: {
      diagnostico: '⚡ DIAGNÓSTICO: Você apresenta alguns sinais que podem indicar desequilíbrio eletrolítico moderado. Um acompanhamento pode ajudar a otimizar seu equilíbrio e prevenir problemas futuros.',
      causaRaiz: '🔍 CAUSA RAIZ: Desequilíbrios eletrolíticos moderados podem causar sintomas intermitentes que muitas vezes passam despercebidos ou são atribuídos a outras causas como cansaço ou estresse. Pesquisas indicam que muitas pessoas vivem com desequilíbrios sutis sem saber que são causados por falta de eletrólitos adequados. Um distribuidor Herbalife pode ajudar a identificar esses padrões sutis, criar um plano de hidratação otimizado e recomendar produtos que sejam adequados ao seu perfil, melhorando sua qualidade de vida e prevenindo que desequilíbrios se tornem mais severos.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Conecte-se com um distribuidor Herbalife para uma avaliação personalizada que pode identificar padrões de hidratação que causam desequilíbrio. Um profissional pode criar estratégias práticas para otimizar sua hidratação, recomendar produtos adequados ao seu perfil e acompanhar sua evolução. Com pequenos ajustes personalizados, você pode melhorar significativamente seu equilíbrio eletrolítico.',
      plano7Dias: '📅 PLANO 7 DIAS: Um distribuidor Herbalife pode criar um plano personalizado que inclui: identificação de padrões de hidratação problemáticos, estratégias práticas para otimizar hidratação e eletrólitos, produtos adequados ao seu perfil, cronograma de observação e ajustes, acompanhamento para monitorar melhorias e suporte para criar hábitos sustentáveis. O acompanhamento regular ajuda a identificar conexões sutis entre hidratação e sintomas.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Com base no seu perfil, um distribuidor Herbalife pode recomendar produtos específicos que otimizam seu equilíbrio eletrolítico, como bebidas eletrolíticas suaves, suplementos de manutenção, produtos para hidratação otimizada e protocolos personalizados. O acompanhamento profissional garante escolhas seguras e eficazes.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um distribuidor Herbalife pode fornecer orientações personalizadas sobre alimentação que otimiza equilíbrio eletrolítico, estratégias para identificar alimentos ricos em eletrólitos, receitas práticas que melhoram sua hidratação, dicas para manter variedade nutricional e suporte para criar hábitos alimentares que promovem bem-estar contínuo. O acompanhamento ajuda a transformar conhecimento em ação prática.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Com um acompanhamento personalizado, você pode otimizar seu equilíbrio eletrolítico e melhorar seu bem-estar. Entre em contato com um distribuidor Herbalife para receber estratégias práticas e produtos adequados ao seu perfil. Pequenos ajustes podem fazer grande diferença na sua qualidade de vida!'
    },
    equilibrioAdequado: {
      diagnostico: '⚡ DIAGNÓSTICO: Você parece ter um bom equilíbrio eletrolítico! Mesmo assim, um acompanhamento preventivo pode ajudar a manter esse equilíbrio e otimizar ainda mais seu bem-estar e energia.',
      causaRaiz: '🔍 CAUSA RAIZ: Ter bom equilíbrio eletrolítico é um grande ativo, mas mesmo pessoas com bom equilíbrio podem se beneficiar de otimizações preventivas. Pesquisas mostram que hábitos de hidratação inadequados ao longo do tempo podem levar ao desenvolvimento de desequilíbrios. Um distribuidor Herbalife pode criar estratégias preventivas personalizadas, recomendar produtos que mantêm o equilíbrio eletrolítico e fornecer orientações para manter seu bem-estar em longo prazo. A prevenção é sempre melhor que o tratamento.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Considere um acompanhamento preventivo com um distribuidor Herbalife para otimizar seu equilíbrio eletrolítico. Um profissional pode criar estratégias personalizadas, recomendar produtos que mantêm o equilíbrio e fornecer orientações para manter sua excelente hidratação ao longo do tempo. A prevenção garante qualidade de vida contínua.',
      plano7Dias: '📅 PLANO 7 DIAS: Um distribuidor Herbalife pode criar um plano preventivo personalizado que inclui: otimização de hidratação e eletrólitos, estratégias para manter equilíbrio eletrolítico, produtos preventivos que mantêm o equilíbrio, orientações sobre combinações ideais de hidratação e nutrição, e acompanhamento para garantir que você mantenha sua excelente condição. A prevenção é a melhor estratégia.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Com base no seu perfil, um distribuidor Herbalife pode recomendar produtos preventivos que mantêm seu equilíbrio eletrolítico, como bebidas eletrolíticas de manutenção, suplementos preventivos, produtos para hidratação otimizada e protocolos personalizados. A suplementação preventiva mantém sua excelente saúde.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um distribuidor Herbalife pode fornecer orientações sobre otimização nutricional preventiva, estratégias para manter excelente equilíbrio eletrolítico, receitas que potencializam bem-estar, dicas sobre combinações alimentares ideais e suporte para criar hábitos que mantêm sua saúde eletrolítica em excelência. A prevenção garante qualidade de vida contínua.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Mantenha seu excelente equilíbrio eletrolítico com estratégias preventivas personalizadas. Entre em contato com um distribuidor Herbalife para receber orientações e produtos que mantêm seu bem-estar. A prevenção é o melhor investimento para sua saúde a longo prazo!'
    }
  }
}

