/**
 * DIAGNÓSTICOS: Avaliação de Intolerância Alimentar - ÁREA WELLNESS
 * 
 * Diagnósticos focados em identificar intolerâncias e sensibilidades alimentares
 * que estimulam contato com distribuidor Herbalife
 */

import { DiagnosticosPorFerramenta } from '../types'

export const intoleranciaDiagnosticos: DiagnosticosPorFerramenta = {
  wellness: {
    altaSuspeitaIntolerancia: {
      diagnostico: '🔍 DIAGNÓSTICO: Seus sintomas indicam alta suspeita de intolerâncias ou sensibilidades alimentares. Um acompanhamento especializado é essencial para identificar os alimentos problemáticos e criar um plano personalizado que melhore sua qualidade de vida.',
      causaRaiz: '🔍 CAUSA RAIZ: Intolerâncias alimentares podem causar sintomas digestivos, inchaço, gases, dores abdominais e até mesmo fadiga. Pesquisas mostram que até 20% da população pode ter alguma intolerância alimentar não diagnosticada. Quando não identificadas, essas sensibilidades podem impactar negativamente a qualidade de vida, energia e bem-estar geral. Um distribuidor Herbalife experiente pode ajudar a identificar padrões alimentares problemáticos e criar um plano personalizado com produtos adequados ao seu perfil, evitando alimentos que causam desconforto e proporcionando nutrição adequada.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Busque um acompanhamento especializado com um distribuidor Herbalife para identificar suas intolerâncias alimentares. Um profissional experiente pode criar um plano de eliminação controlado, recomendar produtos seguros adequados ao seu perfil e acompanhar sua evolução. Produtos Herbalife podem ser uma excelente opção para garantir nutrição completa mesmo com restrições alimentares.',
      plano7Dias: '📅 PLANO 7 DIAS: Conecte-se com um distribuidor Herbalife para receber um plano personalizado que inclui: identificação de alimentos problemáticos, produtos adequados ao seu perfil de intolerância, cronograma de reintrodução controlada, estratégias para manter nutrição adequada mesmo com restrições, acompanhamento diário para monitorar melhorias e ajustes conforme sua resposta individual. O suporte profissional é fundamental para uma transição segura e eficaz.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Um distribuidor Herbalife pode recomendar produtos específicos que são seguros para pessoas com intolerâncias, como Fórmula 1 (que pode ser adaptada), multivitamínicos para garantir nutrição adequada, suplementos para saúde digestiva e produtos que não contenham ingredientes problemáticos. O acompanhamento profissional garante que você receba nutrição completa mesmo com restrições alimentares, evitando deficiências nutricionais.',
      alimentacao: '🍎 ALIMENTAÇÃO: Com o acompanhamento de um distribuidor Herbalife, você receberá orientações personalizadas sobre alimentação adequada ao seu perfil de intolerância, receitas práticas e deliciosas que evitam alimentos problemáticos, estratégias para manter variedade nutricional mesmo com restrições, e suporte constante para criar hábitos alimentares que melhoram sua qualidade de vida. O mentor te ajuda a entender que é possível ter uma alimentação completa e satisfatória mesmo com intolerâncias.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Sua qualidade de vida pode melhorar significativamente ao identificar e tratar adequadamente suas intolerâncias alimentares. Entre em contato com um distribuidor Herbalife para receber um acompanhamento especializado que vai desde produtos adequados ao seu perfil até estratégias personalizadas de alimentação. Você não precisa viver com desconforto — um profissional pode te ajudar a encontrar soluções que transformam seu bem-estar. Sua jornada para uma vida sem desconfortos começa agora!'
    },
    intoleranciaModerada: {
      diagnostico: '🔍 DIAGNÓSTICO: Você apresenta alguns sinais que podem indicar sensibilidade alimentar moderada. Um acompanhamento personalizado pode ajudar a identificar padrões e criar estratégias que otimizem seu bem-estar digestivo.',
      causaRaiz: '🔍 CAUSA RAIZ: Sensibilidades alimentares moderadas podem causar sintomas intermitentes que muitas vezes passam despercebidos ou são atribuídos a outras causas. Pesquisas indicam que muitas pessoas vivem com desconfortos leves a moderados sem saber que são causados por alimentos específicos. Um distribuidor Herbalife pode ajudar a identificar esses padrões sutis, criar um plano alimentar otimizado e recomendar produtos que sejam adequados ao seu perfil, melhorando sua qualidade de vida e prevenindo que sensibilidades se tornem mais severas.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Conecte-se com um distribuidor Herbalife para uma avaliação personalizada que pode identificar padrões alimentares que causam desconforto. Um profissional pode criar estratégias práticas para otimizar sua alimentação, recomendar produtos adequados ao seu perfil e acompanhar sua evolução. Com pequenos ajustes personalizados, você pode melhorar significativamente seu bem-estar digestivo.',
      plano7Dias: '📅 PLANO 7 DIAS: Um distribuidor Herbalife pode criar um plano personalizado que inclui: identificação de padrões alimentares problemáticos, estratégias práticas para otimizar sua alimentação, produtos adequados ao seu perfil, cronograma de observação e ajustes, acompanhamento para monitorar melhorias e suporte para criar hábitos sustentáveis. O acompanhamento regular ajuda a identificar conexões sutis entre alimentos e sintomas.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Com base no seu perfil, um distribuidor Herbalife pode recomendar produtos específicos que otimizam sua saúde digestiva, como probióticos para equilíbrio intestinal, enzimas digestivas para melhor absorção, multivitamínicos para garantir nutrição adequada e produtos que são bem tolerados pelo seu organismo. O acompanhamento profissional garante escolhas seguras e eficazes.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um distribuidor Herbalife pode fornecer orientações personalizadas sobre alimentação otimizada, estratégias para identificar alimentos problemáticos, receitas práticas que melhoram sua digestão, dicas para manter variedade nutricional e suporte para criar hábitos alimentares que promovem bem-estar contínuo. O acompanhamento ajuda a transformar conhecimento em ação prática.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Com um acompanhamento personalizado, você pode otimizar sua alimentação e melhorar seu bem-estar digestivo. Entre em contato com um distribuidor Herbalife para receber estratégias práticas e produtos adequados ao seu perfil. Pequenos ajustes podem fazer grande diferença na sua qualidade de vida!'
    },
    baixaProbabilidadeIntolerancia: {
      diagnostico: '🔍 DIAGNÓSTICO: Você parece ter boa tolerância alimentar. Mesmo assim, um acompanhamento preventivo pode ajudar a otimizar sua alimentação e prevenir futuras sensibilidades, mantendo seu bem-estar em alta.',
      causaRaiz: '🔍 CAUSA RAIZ: Ter boa tolerância alimentar é um grande ativo, mas mesmo pessoas com boa digestão podem se beneficiar de otimizações nutricionais preventivas. Pesquisas mostram que hábitos alimentares inadequados ao longo do tempo podem levar ao desenvolvimento de sensibilidades. Um distribuidor Herbalife pode criar estratégias preventivas personalizadas, recomendar produtos que otimizam sua saúde digestiva e fornecer orientações para manter seu bem-estar em longo prazo. A prevenção é sempre melhor que o tratamento.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Considere um acompanhamento preventivo com um distribuidor Herbalife para otimizar sua alimentação e saúde digestiva. Um profissional pode criar estratégias personalizadas, recomendar produtos que potencializam seu bem-estar e fornecer orientações para manter sua excelente tolerância alimentar ao longo do tempo. A prevenção garante qualidade de vida contínua.',
      plano7Dias: '📅 PLANO 7 DIAS: Um distribuidor Herbalife pode criar um plano preventivo personalizado que inclui: otimização nutricional, estratégias para manter saúde digestiva, produtos que potencializam bem-estar, orientações sobre combinações alimentares ideais, e acompanhamento para garantir que você mantenha sua excelente tolerância alimentar. A prevenção é a melhor estratégia.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Com base no seu perfil, um distribuidor Herbalife pode recomendar produtos preventivos que otimizam sua saúde digestiva, como probióticos para manter equilíbrio intestinal, enzimas digestivas para absorção otimizada, multivitamínicos para nutrição completa e produtos que potencializam seu bem-estar geral. A suplementação preventiva mantém sua excelente saúde.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um distribuidor Herbalife pode fornecer orientações sobre otimização nutricional preventiva, estratégias para manter excelente tolerância alimentar, receitas que potencializam bem-estar, dicas sobre combinações alimentares ideais e suporte para criar hábitos que mantêm sua saúde digestiva em excelência. A prevenção garante qualidade de vida contínua.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Mantenha sua excelente tolerância alimentar com estratégias preventivas personalizadas. Entre em contato com um distribuidor Herbalife para receber orientações e produtos que otimizam seu bem-estar. A prevenção é o melhor investimento para sua saúde a longo prazo!'
    }
  }
}

