/**
 * DIAGNÓSTICOS: Você está Nutrido ou Apenas Alimentado - ÁREA WELLNESS
 * 
 * Diagnósticos focados em diferenciar nutrição de alimentação
 * que estimulam contato com distribuidor Herbalife
 */

import { DiagnosticosPorFerramenta } from '../types'

export const nutridoVsAlimentadoDiagnosticos: DiagnosticosPorFerramenta = {
  wellness: {
    apenasAlimentado: {
      diagnostico: '🍎 DIAGNÓSTICO: Seu perfil indica que você está apenas se alimentando, mas não nutrido adequadamente. Um acompanhamento especializado é essencial para garantir que você receba todos os nutrientes necessários e transforme sua alimentação em nutrição real.',
      causaRaiz: '🔍 CAUSA RAIZ: Alimentar-se sem nutrir adequadamente pode levar a deficiências nutricionais, baixa energia, problemas de saúde, baixa imunidade e piora da qualidade de vida. Pesquisas mostram que até 75% das pessoas se alimentam mas não estão adequadamente nutridas, consumindo calorias vazias sem nutrientes essenciais. Quando não identificado e tratado, esse padrão pode piorar ao longo do tempo. Um distribuidor Herbalife experiente pode ajudar a identificar deficiências nutricionais, criar um plano personalizado para garantir nutrição completa, recomendar produtos específicos para nutrição adequada (como shakes nutritivos completos, suplementos vitamínicos, produtos para energia e bem-estar) e fornecer acompanhamento constante. A combinação de produtos adequados com estratégias nutricionais personalizadas faz toda diferença na transformação de alimentação em nutrição real.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Busque um acompanhamento especializado urgente com um distribuidor Herbalife para garantir nutrição adequada. Um profissional experiente pode criar um plano personalizado que inclui produtos específicos para nutrição completa, estratégias nutricionais otimizadas para garantir todos os nutrientes necessários, receitas nutritivas e práticas, protocolos de suplementação adequados e acompanhamento constante. Produtos Herbalife como shakes nutritivos completos e suplementos vitamínicos podem ser fundamentais para sua jornada de nutrição adequada.',
      plano7Dias: '📅 PLANO 7 DIAS: Conecte-se com um distribuidor Herbalife para receber um plano personalizado que inclui: produtos específicos para nutrição completa, estratégias nutricionais otimizadas para garantir todos os nutrientes essenciais, cronograma detalhado de uso dos produtos, acompanhamento diário para monitorar nutrição, ajustes conforme sua resposta individual e suporte constante. O suporte profissional é fundamental para uma transformação nutricional segura e eficaz.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Um distribuidor Herbalife pode recomendar produtos específicos que garantem nutrição completa, como shakes nutritivos completos de alta qualidade, suplementos vitamínicos e minerais, produtos para energia e bem-estar, multivitamínicos para completar nutrição e protocolos personalizados de suplementação. O acompanhamento profissional garante que você use os produtos certos nas doses adequadas, potencializando resultados e garantindo nutrição completa e adequada.',
      alimentacao: '🍎 ALIMENTAÇÃO: Com o acompanhamento de um distribuidor Herbalife, você receberá orientações personalizadas sobre como transformar alimentação em nutrição, receitas nutritivas e práticas adaptadas ao seu estilo de vida, estratégias de combinação de alimentos para maximizar absorção nutricional, dicas para garantir todos os nutrientes necessários e suporte constante para transformar sua relação com comida. O mentor te ajuda a entender como cada alimento contribui para sua nutrição adequada.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Sua saúde pode melhorar significativamente ao garantir nutrição adequada. Entre em contato com um distribuidor Herbalife para receber um acompanhamento especializado urgente que vai desde produtos específicos para nutrição completa até estratégias personalizadas de nutrição. Você não precisa conviver com alimentação sem nutrição adequada — um profissional pode te ajudar a encontrar soluções que transformam seu bem-estar. Sua jornada para nutrição adequada começa agora!'
    },
    parcialmenteNutrido: {
      diagnostico: '🍎 DIAGNÓSTICO: Você está parcialmente nutrido, mas pode ser otimizado. Um acompanhamento pode ajudar a garantir que você receba todos os nutrientes necessários e transforme sua alimentação em nutrição completa.',
      causaRaiz: '🔍 CAUSA RAIZ: Nutrição parcial indica boa base, mas há oportunidades de otimização para garantir nutrição completa. Pesquisas indicam que muitas pessoas têm algum nível de nutrição mas podem garantir nutrição mais completa e adequada. Um distribuidor Herbalife pode ajudar a identificar oportunidades específicas de otimização nutricional, criar estratégias personalizadas e recomendar produtos que garantem nutrição completa, elevando seus resultados para o próximo nível.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Conecte-se com um distribuidor Herbalife para receber estratégias de otimização nutricional personalizadas. Um profissional pode criar um plano que inclui produtos que garantem nutrição completa, estratégias nutricionais otimizadas, ajustes no estilo de vida e acompanhamento para garantir que você alcance nutrição adequada e completa. Com pequenos ajustes personalizados, você pode melhorar significativamente sua nutrição.',
      plano7Dias: '📅 PLANO 7 DIAS: Um distribuidor Herbalife pode criar um plano de otimização nutricional que inclui: produtos que garantem nutrição completa, estratégias nutricionais otimizadas, ajustes no timing das refeições, protocolo de suplementação adequado, acompanhamento para monitorar melhorias e ajustes conforme seu progresso individual. O acompanhamento regular garante otimização contínua.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Com base no seu perfil, um distribuidor Herbalife pode recomendar produtos que otimizam sua nutrição, como shakes nutritivos completos, suplementos de manutenção, produtos para energia e protocolos personalizados. O acompanhamento profissional garante escolhas adequadas e maximiza nutrição.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um distribuidor Herbalife pode fornecer orientações sobre otimização nutricional, estratégias de timing alimentar, combinações de alimentos que maximizam absorção nutricional, receitas práticas e suporte para criar hábitos que mantêm nutrição otimizada. O acompanhamento ajuda a transformar conhecimento em ação prática.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Com estratégias personalizadas, você pode otimizar sua nutrição e melhorar seus resultados. Entre em contato com um distribuidor Herbalife para receber um plano de otimização nutricional. Produtos adequados e estratégias personalizadas podem fazer toda diferença na sua nutrição completa!'
    },
    bemNutrido: {
      diagnostico: '🍎 DIAGNÓSTICO: Você já está bem nutrido! Mesmo assim, um acompanhamento preventivo pode ajudar a manter essa nutrição adequada e otimizar ainda mais sua saúde nutricional.',
      causaRaiz: '🔍 CAUSA RAIZ: Ter boa nutrição é um grande ativo, mas pode ser otimizado ainda mais com estratégias preventivas e produtos adequados. Pesquisas mostram que nutrição pode ser mantida e otimizada continuamente. Um distribuidor Herbalife pode criar estratégias preventivas personalizadas, recomendar produtos que mantêm nutrição adequada e fornecer orientações para manter seu bem-estar em longo prazo. A prevenção é sempre melhor que o tratamento.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Considere um acompanhamento preventivo com um distribuidor Herbalife para otimizar sua nutrição. Um profissional pode criar estratégias personalizadas, recomendar produtos que mantêm nutrição adequada e fornecer orientações para manter sua excelente condição ao longo do tempo. A prevenção garante qualidade de vida contínua.',
      plano7Dias: '📅 PLANO 7 DIAS: Um distribuidor Herbalife pode criar um plano preventivo personalizado que inclui: otimização de nutrição, estratégias para manter nutrição adequada, produtos preventivos que mantêm nutrição, orientações sobre combinações ideais de alimentos e acompanhamento para garantir que você mantenha sua excelente condição. A prevenção é a melhor estratégia.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Com base no seu perfil, um distribuidor Herbalife pode recomendar produtos preventivos que mantêm sua nutrição adequada, como shakes de manutenção, suplementos preventivos, produtos para nutrição otimizada e protocolos personalizados. A suplementação preventiva mantém sua excelente saúde.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um distribuidor Herbalife pode fornecer orientações sobre otimização nutricional preventiva, estratégias para manter excelente nutrição, receitas que potencializam bem-estar, dicas sobre combinações alimentares ideais e suporte para criar hábitos que mantêm sua nutrição adequada em excelência. A prevenção garante qualidade de vida contínua.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Mantenha sua excelente nutrição com estratégias preventivas personalizadas. Entre em contato com um distribuidor Herbalife para receber orientações e produtos que mantêm seu bem-estar. A prevenção é o melhor investimento para sua saúde a longo prazo!'
    }
  }
}

