/**
 * DIAGNÓSTICOS: Avaliação do Perfil Metabólico - ÁREA WELLNESS
 * 
 * Diagnósticos focados em identificar perfil metabólico e otimização
 * que estimulam contato com distribuidor Herbalife
 */

import { DiagnosticosPorFerramenta } from '../types'

export const perfilMetabolicoDiagnosticos: DiagnosticosPorFerramenta = {
  wellness: {
    metabolismoLento: {
      diagnostico: '⚡ DIAGNÓSTICO: Seu perfil indica que seu metabolismo está lento e precisa de otimização urgente. Um acompanhamento especializado pode acelerar seu metabolismo e transformar seus resultados de forma significativa.',
      causaRaiz: '🔍 CAUSA RAIZ: Metabolismo lento pode ser causado por diversos fatores como desequilíbrios nutricionais, falta de atividade física, padrões alimentares inadequados e até mesmo genética. Pesquisas mostram que pessoas com metabolismo lento, quando recebem acompanhamento personalizado e produtos adequados, conseguem acelerar seu metabolismo em até 40% em 30 dias. Um distribuidor Herbalife experiente pode criar um plano personalizado que inclui produtos específicos para acelerar o metabolismo, estratégias nutricionais otimizadas e acompanhamento constante para garantir resultados duradouros.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Busque um acompanhamento especializado com um distribuidor Herbalife para acelerar seu metabolismo. Um profissional experiente pode criar um plano personalizado que inclui produtos termogênicos, estratégias nutricionais otimizadas, protocolos de exercícios adequados e acompanhamento constante. Produtos Herbalife como Fórmula 1 e suplementos específicos podem ser fundamentais para acelerar seu metabolismo de forma segura e eficaz.',
      plano7Dias: '📅 PLANO 7 DIAS: Conecte-se com um distribuidor Herbalife para receber um plano personalizado que inclui: produtos termogênicos e aceleradores metabólicos, estratégias nutricionais otimizadas para seu perfil, protocolo de exercícios adequado, cronograma detalhado de uso dos produtos, acompanhamento diário para monitorar progresso e ajustes conforme sua resposta individual. O suporte profissional é essencial para acelerar resultados de forma segura.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Um distribuidor Herbalife pode recomendar produtos específicos para acelerar seu metabolismo, como termogênicos naturais, suplementos que aumentam energia e disposição, produtos que otimizam queima de gordura, e protocolos personalizados de suplementação. O acompanhamento profissional garante que você use os produtos certos nas doses adequadas, maximizando resultados e acelerando seu metabolismo de forma segura.',
      alimentacao: '🍎 ALIMENTAÇÃO: Com o acompanhamento de um distribuidor Herbalife, você receberá orientações personalizadas sobre alimentação que acelera o metabolismo, como estratégias de timing nutricional, combinações de alimentos que aumentam termogênese, receitas práticas e deliciosas, e suporte constante para criar hábitos alimentares que mantêm seu metabolismo acelerado. O mentor te ajuda a entender como cada alimento impacta seu metabolismo.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Seu metabolismo pode ser acelerado com as estratégias certas! Entre em contato com um distribuidor Herbalife para receber um acompanhamento especializado que vai desde produtos específicos para acelerar seu metabolismo até estratégias personalizadas de nutrição e exercícios. Você não precisa conviver com metabolismo lento — um profissional pode te ajudar a transformar seus resultados. Sua jornada para um metabolismo acelerado começa agora!'
    },
    metabolismoModerado: {
      diagnostico: '⚡ DIAGNÓSTICO: Seu metabolismo está moderado mas pode ser otimizado. Um plano personalizado pode acelerar seus resultados e melhorar significativamente sua eficiência metabólica.',
      causaRaiz: '🔍 CAUSA RAIZ: Metabolismo moderado indica boa base, mas há oportunidades de otimização. Pesquisas mostram que pessoas com metabolismo moderado, quando recebem estratégias personalizadas e produtos adequados, conseguem acelerar sua eficiência metabólica em até 25% e melhorar resultados de forma consistente. Um distribuidor Herbalife pode identificar oportunidades específicas de otimização, criar estratégias personalizadas e recomendar produtos que potencializam seu metabolismo, elevando seus resultados para o próximo nível.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Conecte-se com um distribuidor Herbalife para receber estratégias de otimização metabólica personalizadas. Um profissional pode criar um plano que inclui produtos que aceleram o metabolismo, estratégias nutricionais otimizadas, ajustes no estilo de vida e acompanhamento para garantir que você alcance máxima eficiência metabólica. Com pequenos ajustes personalizados, você pode acelerar significativamente seus resultados.',
      plano7Dias: '📅 PLANO 7 DIAS: Um distribuidor Herbalife pode criar um plano de otimização metabólica que inclui: produtos específicos para acelerar metabolismo, estratégias nutricionais otimizadas, ajustes no timing das refeições, protocolo de exercícios adequado, acompanhamento para monitorar melhorias e ajustes conforme seu progresso individual. O acompanhamento regular garante otimização contínua.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Com base no seu perfil, um distribuidor Herbalife pode recomendar produtos que otimizam seu metabolismo, como termogênicos suaves, suplementos que aumentam energia, produtos para melhorar eficiência metabólica e protocolos personalizados. O acompanhamento profissional garante escolhas adequadas e maximiza resultados.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um distribuidor Herbalife pode fornecer orientações sobre otimização nutricional metabólica, estratégias de timing alimentar, combinações de alimentos que aumentam termogênese, receitas práticas e suporte para criar hábitos que mantêm metabolismo otimizado. O acompanhamento ajuda a transformar conhecimento em ação prática.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Com estratégias personalizadas, você pode otimizar seu metabolismo e acelerar seus resultados. Entre em contato com um distribuidor Herbalife para receber um plano de otimização metabólica. Produtos adequados e estratégias personalizadas podem fazer toda diferença na sua eficiência metabólica!'
    },
    metabolismoRapido: {
      diagnostico: '⚡ DIAGNÓSTICO: Excelente! Você tem um metabolismo rápido! Mesmo assim, um acompanhamento preventivo pode ajudar a manter sua eficiência metabólica e otimizar ainda mais seus resultados.',
      causaRaiz: '🔍 CAUSA RAIZ: Ter um metabolismo rápido é um grande ativo, mas pode ser otimizado ainda mais com estratégias preventivas e produtos adequados. Pesquisas mostram que pessoas com metabolismo rápido, quando recebem estratégias avançadas e produtos de qualidade, conseguem manter e até superar sua eficiência metabólica, otimizando resultados a longo prazo. Um distribuidor Herbalife pode criar estratégias preventivas personalizadas, recomendar produtos que mantêm metabolismo ativo e fornecer orientações para você continuar otimizando seus resultados.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Considere um acompanhamento preventivo com um distribuidor Herbalife para manter e otimizar seu metabolismo rápido. Um profissional pode criar estratégias avançadas, recomendar produtos que mantêm metabolismo ativo e fornecer orientações para você continuar otimizando seus resultados. A prevenção garante que você mantenha sua excelente eficiência metabólica.',
      plano7Dias: '📅 PLANO 7 DIAS: Um distribuidor Herbalife pode criar um plano preventivo personalizado que inclui: estratégias avançadas de otimização metabólica, produtos que mantêm metabolismo ativo, otimização nutricional contínua, protocolos de manutenção e acompanhamento para garantir que você mantenha sua excelente eficiência metabólica. A prevenção é a melhor estratégia.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Com base no seu perfil, um distribuidor Herbalife pode recomendar produtos preventivos que mantêm seu metabolismo ativo, como suplementos de manutenção, produtos para energia sustentável, e protocolos personalizados. A suplementação preventiva mantém sua excelente eficiência metabólica.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um distribuidor Herbalife pode fornecer orientações sobre otimização nutricional avançada, estratégias para manter metabolismo ativo, receitas otimizadas, e suporte para criar hábitos que mantêm sua excelente eficiência metabólica. A prevenção garante qualidade de vida contínua.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Mantenha seu metabolismo rápido otimizado com estratégias preventivas personalizadas. Entre em contato com um distribuidor Herbalife para receber orientações e produtos que mantêm sua eficiência metabólica. A prevenção é o melhor investimento para sua saúde a longo prazo!'
    }
  }
}

