/**
 * DIAGNÓSTICOS: Pronto para Emagrecer com Saúde - ÁREA WELLNESS
 * 
 * Diagnósticos focados em identificar prontidão para emagrecimento saudável
 * que estimulam contato com distribuidor Herbalife
 */

import { DiagnosticosPorFerramenta } from '../types'

export const prontoEmagrecerDiagnosticos: DiagnosticosPorFerramenta = {
  wellness: {
    altoPotencialEmagrecer: {
      diagnostico: '🎯 DIAGNÓSTICO: Excelente! Você está muito motivado(a) e pronto(a) para emagrecer com saúde. Seu perfil indica alto potencial para resultados excepcionais com o acompanhamento certo.',
      causaRaiz: '🔍 CAUSA RAIZ: Você demonstrou motivação alta, abertura para orientação profissional, valorização de planos personalizados e crença em produtos de qualidade. Pesquisas mostram que pessoas com esse perfil, quando recebem acompanhamento especializado e produtos premium, conseguem resultados 3x superiores e sustentáveis no emagrecimento. Um distribuidor Herbalife experiente pode criar um programa VIP personalizado que inclui produtos premium para emagrecimento saudável, estratégias avançadas de nutrição e exercícios, mentoria especializada e acompanhamento intensivo. Com sua motivação e o suporte adequado, você pode alcançar transformações excepcionais e manter os resultados a longo prazo.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Conecte-se com um distribuidor Herbalife experiente para acessar programas VIP de emagrecimento, produtos premium da linha Herbalife e estratégias avançadas de transformação. Com sua motivação excepcional, você está pronto(a) para resultados excepcionais. Um mentor especializado pode criar um programa personalizado de alto desempenho, potencializar ainda mais seu potencial e te guiar para o próximo nível de emagrecimento saudável. Você tem tudo para se tornar referência!',
      plano7Dias: '📅 PLANO 7 DIAS: Um distribuidor Herbalife pode criar um programa VIP personalizado de emagrecimento que inclui: produtos premium para emagrecimento saudável, estratégias avançadas de nutrição e exercícios, acompanhamento intensivo diário, mentoria especializada, protocolos de otimização, ajustes imediatos conforme seu progresso e estratégias de longo prazo para manutenção. Com sua motivação excepcional e suporte de elite, você pode alcançar resultados excepcionais em tempo recorde.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Com seu perfil de alto potencial, um distribuidor Herbalife pode recomendar produtos premium da linha Herbalife específicos para emagrecimento saudável, como shakes de alta qualidade, suplementos que aceleram metabolismo, produtos para controle de fome, multivitamínicos avançados e protocolos de suplementação estratégica. O acompanhamento profissional garante uso otimizado e maximiza cada resultado.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um distribuidor Herbalife pode fornecer estratégias avançadas de alimentação para emagrecimento, programas premium com receitas deliciosas e nutritivas, técnicas de timing nutricional, combinações otimizadas de alimentos, protocolos de performance e mentoria especializada em nutrição para emagrecimento saudável. Com sua motivação excepcional, você está pronto(a) para resultados excepcionais e pode se tornar referência em transformação.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Parabéns! Com sua motivação excepcional, você está pronto(a) para resultados excepcionais no emagrecimento. Entre em contato com um distribuidor Herbalife experiente para acessar programas VIP personalizados, produtos premium que potencializam seu emagrecimento e mentoria especializada de alto desempenho. Vamos levar você ao próximo nível de transformação e fazer você brilhar como referência! Sua transformação excepcional começa agora!'
    },
    prontoParaEmagrecer: {
      diagnostico: '🎯 DIAGNÓSTICO: Você está pronto(a) para começar sua jornada de emagrecimento! Um acompanhamento personalizado pode acelerar seus resultados e te guiar em cada etapa da sua transformação.',
      causaRaiz: '🔍 CAUSA RAIZ: Você demonstrou motivação, abertura para orientação profissional e valorização de planos personalizados. Pesquisas mostram que pessoas com esse perfil, quando recebem acompanhamento personalizado e produtos de qualidade, alcançam resultados 2,5x mais rápido no emagrecimento do que tentando sozinhas. Um distribuidor Herbalife pode criar um plano personalizado que inclui produtos adequados ao seu perfil de emagrecimento, estratégias práticas de nutrição e exercícios, acompanhamento regular e suporte emocional. Com sua motivação e o suporte certo, você pode transformar seus objetivos em resultados concretos.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Conecte-se com um distribuidor Herbalife para receber um programa personalizado de emagrecimento que inclui produtos adequados aos seus objetivos, estratégias práticas de nutrição e exercícios, acompanhamento regular por WhatsApp, check-ins semanais para ajustes e suporte emocional quando necessário. Com sua motivação atual e o suporte certo, você pode alcançar resultados muito mais rápido e manter consistência ao longo do tempo.',
      plano7Dias: '📅 PLANO 7 DIAS: Um distribuidor Herbalife pode criar um plano personalizado de emagrecimento que inclui: produtos específicos para seu perfil, cronograma detalhado de uso, estratégias de motivação diária, check-ins regulares para acompanhar progresso, ajustes conforme sua resposta individual e celebração de conquistas. O acompanhamento regular mantém sua motivação elevada, garante que você siga o plano corretamente e previne desistências.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Com base no seu perfil e objetivos de emagrecimento, um distribuidor Herbalife pode recomendar produtos específicos que potencializam seus resultados, como shakes de alta qualidade, suplementos que aceleram metabolismo, produtos para controle de fome, multivitamínicos para energia constante. O acompanhamento profissional garante uso correto e maximiza resultados.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um distribuidor Herbalife pode fornecer orientações personalizadas sobre alimentação para emagrecimento saudável, receitas práticas e deliciosas adaptadas ao seu estilo de vida, estratégias de combinação de alimentos para maximizar resultados, dicas para manter motivação mesmo nos dias difíceis e suporte para criar hábitos duradouros. O acompanhamento ajuda a transformar conhecimento em ação prática, potencializando resultados e criando mudanças sustentáveis.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Com sua motivação atual, você está pronto(a) para acelerar resultados no emagrecimento. Entre em contato com um distribuidor Herbalife para receber um programa personalizado que potencializa sua transformação. Com produtos adequados, estratégias práticas e acompanhamento regular, você pode alcançar seus objetivos muito mais rápido. Estamos prontos para ajudar você a transformar sua motivação em resultados concretos!'
    },
    precisaMaisInformacoesEmagrecer: {
      diagnostico: '🎯 DIAGNÓSTICO: Você está no início da sua jornada de emagrecimento. Um acompanhamento pode te ajudar a entender melhor suas necessidades e criar um plano adequado para você começar com segurança e confiança.',
      causaRaiz: '🔍 CAUSA RAIZ: Você está explorando possibilidades e buscando informações antes de começar sua jornada de emagrecimento. Isso é muito positivo! Pesquisas mostram que pessoas que buscam informações adequadas antes de começar têm maior taxa de sucesso a longo prazo no emagrecimento. Um distribuidor Herbalife pode te ajudar a entender suas necessidades, explicar opções disponíveis, apresentar produtos adequados ao seu perfil de emagrecimento e criar um plano inicial que te deixe confortável para começar. O suporte educacional é fundamental para construir confiança e segurança.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Conecte-se com um distribuidor Herbalife para uma conversa inicial sem compromisso. Um profissional experiente pode te ajudar a entender suas necessidades, explicar opções disponíveis para emagrecimento, apresentar produtos adequados ao seu perfil e responder suas dúvidas. Essa conversa inicial te ajuda a tomar decisões informadas e começar sua jornada com confiança e segurança.',
      plano7Dias: '📅 PLANO 7 DIAS: Um distribuidor Herbalife pode criar um plano inicial educacional que inclui: explicação sobre suas necessidades identificadas, apresentação de produtos adequados ao seu perfil de emagrecimento, estratégias básicas para começar, cronograma inicial de adaptação, acompanhamento para esclarecer dúvidas e ajustes conforme sua compreensão. O suporte educacional é fundamental para construir confiança.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Um distribuidor Herbalife pode apresentar produtos básicos adequados ao seu perfil de emagrecimento, explicar benefícios de cada produto, recomendar protocolo inicial simples e fornecer orientações sobre uso correto. O acompanhamento profissional garante que você entenda como usar os produtos e comece com segurança.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um distribuidor Herbalife pode fornecer orientações básicas sobre alimentação para emagrecimento saudável, receitas simples e práticas, estratégias para começar gradualmente e suporte para esclarecer dúvidas. O acompanhamento educacional ajuda a construir conhecimento e confiança para começar sua jornada.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Sua jornada de emagrecimento começa com informações adequadas. Entre em contato com um distribuidor Herbalife para uma conversa inicial sem compromisso. Um profissional pode te ajudar a entender suas necessidades, explicar opções disponíveis e criar um plano inicial que te deixe confortável para começar. Você não precisa ter todas as respostas agora — estamos aqui para ajudar você a descobrir o caminho certo!'
    }
  }
}

