/**
 * DIAGNÓSTICOS: Teste de Retenção de Líquidos - ÁREA WELLNESS
 * 
 * Diagnósticos focados em identificar retenção de líquidos
 * que estimulam contato com distribuidor Herbalife
 */

import { DiagnosticosPorFerramenta } from '../types'

export const retencaoLiquidosDiagnosticos: DiagnosticosPorFerramenta = {
  wellness: {
    retencaoAlta: {
      diagnostico: '💧 DIAGNÓSTICO: Seu perfil indica retenção alta de líquidos. Um acompanhamento especializado é essencial para identificar causas e criar estratégias personalizadas para reduzir o inchaço e melhorar significativamente seu bem-estar.',
      causaRaiz: '🔍 CAUSA RAIZ: Retenção de líquidos pode ser causada por desequilíbrios hormonais, excesso de sódio, falta de potássio, problemas circulatórios, sedentarismo ou condições médicas específicas. Pesquisas mostram que até 50% das mulheres podem apresentar retenção durante o ciclo menstrual. Quando não identificada e tratada adequadamente, a retenção pode piorar e afetar qualidade de vida. Um distribuidor Herbalife experiente pode ajudar a identificar fatores causadores, criar um plano personalizado para reduzir retenção, recomendar produtos específicos (como suplementos diuréticos naturais, produtos para circulação, produtos para equilíbrio eletrolítico) e fornecer acompanhamento constante. A combinação de produtos adequados com estratégias nutricionais e de estilo de vida personalizadas faz toda diferença na redução de retenção.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Busque um acompanhamento especializado urgente com um distribuidor Herbalife para reduzir retenção de líquidos. Um profissional experiente pode criar um plano personalizado que inclui produtos específicos para retenção, estratégias nutricionais otimizadas (redução de sódio, aumento de potássio), protocolos de exercícios adequados e acompanhamento constante. Produtos Herbalife como suplementos diuréticos naturais e produtos para circulação podem ser fundamentais para sua jornada de redução de retenção.',
      plano7Dias: '📅 PLANO 7 DIAS: Conecte-se com um distribuidor Herbalife para receber um plano personalizado que inclui: produtos específicos para reduzir retenção, estratégias nutricionais otimizadas (redução de sódio, aumento de potássio), protocolos de exercícios adequados (movimento e alongamento), cronograma detalhado de uso dos produtos, acompanhamento diário para monitorar progresso e ajustes conforme sua resposta individual. O suporte profissional é fundamental para uma redução de retenção segura e eficaz.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Um distribuidor Herbalife pode recomendar produtos específicos que ajudam a reduzir retenção de líquidos, como suplementos diuréticos naturais, produtos para circulação, produtos para equilíbrio eletrolítico, multivitamínicos para suporte geral e protocolos personalizados de suplementação. O acompanhamento profissional garante que você use os produtos certos nas doses adequadas, potencializando resultados e reduzindo retenção de forma segura.',
      alimentacao: '🍎 ALIMENTAÇÃO: Com o acompanhamento de um distribuidor Herbalife, você receberá orientações personalizadas sobre alimentação que reduz retenção, como alimentos ricos em potássio (banana, abacate), redução de sódio, alimentos diuréticos naturais (pepino, melancia), estratégias de hidratação adequada e suporte constante para criar hábitos alimentares que reduzem retenção. O mentor te ajuda a entender como cada alimento impacta sua retenção de líquidos.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Sua qualidade de vida pode melhorar significativamente ao reduzir retenção de líquidos. Entre em contato com um distribuidor Herbalife para receber um acompanhamento especializado urgente que vai desde produtos específicos para retenção até estratégias personalizadas de redução. Você não precisa conviver com inchaço e desconforto — um profissional pode te ajudar a encontrar soluções que transformam seu bem-estar. Sua jornada para redução de retenção começa agora!'
    },
    retencaoModerada: {
      diagnostico: '💧 DIAGNÓSTICO: Você apresenta retenção moderada. Um acompanhamento preventivo pode ajudar a reduzir a retenção e manter seu corpo em equilíbrio hidroeletrolítico.',
      causaRaiz: '🔍 CAUSA RAIZ: Retenção moderada indica que você tem alguns fatores que podem ser identificados e tratados com estratégias preventivas adequadas. Pesquisas indicam que muitas pessoas têm retenção moderada não identificada que pode ser prevenida. Um distribuidor Herbalife pode ajudar a identificar fatores específicos, criar estratégias preventivas personalizadas e recomendar produtos adequados ao seu perfil, melhorando seu equilíbrio hidroeletrolítico e prevenindo desconfortos futuros.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Conecte-se com um distribuidor Herbalife para uma avaliação preventiva que pode identificar seus fatores de retenção específicos. Um profissional pode criar estratégias práticas para reduzir retenção, recomendar produtos adequados ao seu perfil e acompanhar sua evolução. Com pequenos ajustes personalizados, você pode melhorar significativamente seu equilíbrio hidroeletrolítico.',
      plano7Dias: '📅 PLANO 7 DIAS: Um distribuidor Herbalife pode criar um plano preventivo personalizado que inclui: identificação de fatores de retenção, estratégias práticas para redução, produtos adequados ao seu perfil, cronograma de observação e ajustes, acompanhamento para monitorar melhorias e suporte para criar hábitos sustentáveis. O acompanhamento regular ajuda a identificar melhorias no equilíbrio hidroeletrolítico.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Com base no seu perfil, um distribuidor Herbalife pode recomendar produtos específicos que reduzem retenção moderada, como produtos leves para circulação, suplementos para equilíbrio eletrolítico, produtos de manutenção e protocolos personalizados. O acompanhamento profissional garante escolhas seguras e eficazes.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um distribuidor Herbalife pode fornecer orientações personalizadas sobre alimentação que reduz retenção, estratégias para identificar padrões problemáticos, receitas práticas que melhoram equilíbrio hidroeletrolítico, dicas para manter variedade nutricional e suporte para criar hábitos alimentares que promovem bem-estar contínuo. O acompanhamento ajuda a transformar conhecimento em ação prática.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Com um acompanhamento personalizado, você pode reduzir sua retenção moderada e melhorar seu bem-estar. Entre em contato com um distribuidor Herbalife para receber estratégias práticas e produtos adequados ao seu perfil. Pequenos ajustes podem fazer grande diferença na sua qualidade de vida!'
    },
    retencaoBaixa: {
      diagnostico: '💧 DIAGNÓSTICO: Você tem baixa retenção! Mesmo assim, um acompanhamento preventivo pode ajudar a manter esse equilíbrio e otimizar ainda mais sua saúde hidroeletrolítica.',
      causaRaiz: '🔍 CAUSA RAIZ: Ter baixa retenção é um grande ativo, mas pode ser mantido e otimizado ainda mais com estratégias preventivas adequadas. Pesquisas mostram que hábitos inadequados ao longo do tempo podem aumentar retenção. Um distribuidor Herbalife pode criar estratégias preventivas personalizadas, recomendar produtos que mantêm equilíbrio hidroeletrolítico e fornecer orientações para manter seu bem-estar em longo prazo. A prevenção é sempre melhor que o tratamento.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Considere um acompanhamento preventivo com um distribuidor Herbalife para manter sua baixa retenção. Um profissional pode criar estratégias personalizadas, recomendar produtos que mantêm equilíbrio hidroeletrolítico e fornecer orientações para manter sua excelente condição ao longo do tempo. A prevenção garante qualidade de vida contínua.',
      plano7Dias: '📅 PLANO 7 DIAS: Um distribuidor Herbalife pode criar um plano preventivo personalizado que inclui: otimização de equilíbrio hidroeletrolítico, estratégias para manter baixa retenção, produtos preventivos que mantêm equilíbrio, orientações sobre combinações ideais de alimentos e acompanhamento para garantir que você mantenha sua excelente condição. A prevenção é a melhor estratégia.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Com base no seu perfil, um distribuidor Herbalife pode recomendar produtos preventivos que mantêm sua baixa retenção, como produtos de manutenção, suplementos preventivos, produtos para equilíbrio eletrolítico e protocolos personalizados. A suplementação preventiva mantém sua excelente saúde.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um distribuidor Herbalife pode fornecer orientações sobre otimização nutricional preventiva, estratégias para manter excelente equilíbrio hidroeletrolítico, receitas que potencializam bem-estar, dicas sobre combinações alimentares ideais e suporte para criar hábitos que mantêm sua baixa retenção em excelência. A prevenção garante qualidade de vida contínua.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Mantenha sua baixa retenção com estratégias preventivas personalizadas. Entre em contato com um distribuidor Herbalife para receber orientações e produtos que mantêm seu bem-estar. A prevenção é o melhor investimento para sua saúde a longo prazo!'
    }
  }
}

