/**
 * DIAGNÓSTICOS: Risco de Síndrome Metabólica - ÁREA WELLNESS
 * 
 * Diagnósticos focados em identificar risco de síndrome metabólica
 * que estimulam contato com distribuidor Herbalife
 */

import { DiagnosticosPorFerramenta } from '../types'

export const sindromeMetabolicaDiagnosticos: DiagnosticosPorFerramenta = {
  wellness: {
    riscoAlto: {
      diagnostico: '⚠️ DIAGNÓSTICO: Seu perfil indica risco alto para síndrome metabólica. Um acompanhamento especializado é essencial para prevenir complicações e melhorar significativamente sua saúde metabólica.',
      causaRaiz: '🔍 CAUSA RAIZ: Síndrome metabólica é caracterizada por um conjunto de fatores de risco (obesidade abdominal, pressão alta, glicemia elevada, triglicerídeos altos, colesterol HDL baixo) que aumentam risco de doenças cardiovasculares e diabetes. Pesquisas mostram que até 35% da população adulta pode ter síndrome metabólica não diagnosticada. Quando não identificados e tratados, esses fatores podem levar a complicações graves. Um distribuidor Herbalife experiente pode ajudar a identificar fatores de risco, criar um plano preventivo personalizado, recomendar produtos específicos para saúde metabólica (como produtos para controle de peso, suplementos para saúde cardiovascular, produtos para controle glicêmico) e fornecer acompanhamento constante. A combinação de produtos adequados com estratégias preventivas personalizadas faz toda diferença na redução de riscos.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Busque um acompanhamento especializado urgente com um distribuidor Herbalife para reduzir seu risco de síndrome metabólica. Um profissional experiente pode criar um plano preventivo personalizado que inclui produtos específicos para saúde metabólica, estratégias nutricionais otimizadas, protocolos de exercícios adequados e acompanhamento constante. Produtos Herbalife como shakes para controle de peso e suplementos para saúde cardiovascular podem ser fundamentais para sua jornada preventiva.',
      plano7Dias: '📅 PLANO 7 DIAS: Conecte-se com um distribuidor Herbalife para receber um plano preventivo personalizado que inclui: produtos específicos para reduzir riscos metabólicos, estratégias nutricionais otimizadas, protocolos de exercícios adequados, cronograma detalhado de uso dos produtos, acompanhamento diário para monitorar progresso e ajustes conforme sua resposta individual. O suporte profissional é fundamental para uma redução de riscos segura e eficaz.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Um distribuidor Herbalife pode recomendar produtos específicos que ajudam a reduzir riscos metabólicos, como shakes para controle de peso, suplementos para saúde cardiovascular, produtos para controle glicêmico, multivitamínicos para suporte geral e protocolos personalizados de suplementação. O acompanhamento profissional garante que você use os produtos certos nas doses adequadas, potencializando resultados e reduzindo riscos.',
      alimentacao: '🍎 ALIMENTAÇÃO: Com o acompanhamento de um distribuidor Herbalife, você receberá orientações personalizadas sobre alimentação que reduz riscos metabólicos, como alimentos que melhoram saúde cardiovascular, estratégias de combinação de alimentos, receitas práticas e deliciosas, e suporte constante para criar hábitos alimentares que reduzem riscos. O mentor te ajuda a entender como cada alimento impacta sua saúde metabólica.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Sua saúde metabólica pode melhorar significativamente ao reduzir fatores de risco. Entre em contato com um distribuidor Herbalife para receber um acompanhamento especializado urgente que vai desde produtos específicos para saúde metabólica até estratégias personalizadas de prevenção. Você não precisa conviver com alto risco — um profissional pode te ajudar a encontrar soluções que transformam seu bem-estar. Sua jornada para redução de riscos começa agora!'
    },
    riscoModerado: {
      diagnostico: '⚠️ DIAGNÓSTICO: Você apresenta risco moderado. Um acompanhamento preventivo pode ajudar a reduzir riscos e manter sua saúde metabólica em equilíbrio.',
      causaRaiz: '🔍 CAUSA RAIZ: Risco moderado indica que você tem alguns fatores de risco que podem ser reduzidos com estratégias preventivas adequadas. Pesquisas indicam que muitas pessoas têm riscos moderados não identificados que podem ser prevenidos. Um distribuidor Herbalife pode ajudar a identificar fatores de risco específicos, criar estratégias preventivas personalizadas e recomendar produtos adequados ao seu perfil, melhorando sua saúde metabólica e prevenindo complicações futuras.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Conecte-se com um distribuidor Herbalife para uma avaliação preventiva que pode identificar seus fatores de risco específicos. Um profissional pode criar estratégias práticas para reduzir riscos, recomendar produtos adequados ao seu perfil e acompanhar sua evolução. Com pequenos ajustes personalizados, você pode melhorar significativamente sua saúde metabólica.',
      plano7Dias: '📅 PLANO 7 DIAS: Um distribuidor Herbalife pode criar um plano preventivo personalizado que inclui: identificação de fatores de risco, estratégias práticas para redução de riscos, produtos adequados ao seu perfil, cronograma de observação e ajustes, acompanhamento para monitorar melhorias e suporte para criar hábitos sustentáveis. O acompanhamento regular ajuda a identificar melhorias nos fatores de risco.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Com base no seu perfil, um distribuidor Herbalife pode recomendar produtos específicos que reduzem riscos metabólicos, como produtos para controle de peso, suplementos para saúde cardiovascular, produtos de manutenção e protocolos personalizados. O acompanhamento profissional garante escolhas seguras e eficazes.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um distribuidor Herbalife pode fornecer orientações personalizadas sobre alimentação que reduz riscos, estratégias para identificar padrões problemáticos, receitas práticas que melhoram saúde metabólica, dicas para manter variedade nutricional e suporte para criar hábitos alimentares que promovem bem-estar contínuo. O acompanhamento ajuda a transformar conhecimento em ação prática.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Com um acompanhamento personalizado, você pode reduzir seus riscos metabólicos e melhorar seu bem-estar. Entre em contato com um distribuidor Herbalife para receber estratégias práticas e produtos adequados ao seu perfil. Pequenos ajustes podem fazer grande diferença na sua qualidade de vida!'
    },
    riscoBaixo: {
      diagnostico: '⚠️ DIAGNÓSTICO: Você tem baixo risco! Mesmo assim, um acompanhamento preventivo pode ajudar a manter esse risco baixo e otimizar ainda mais sua saúde metabólica.',
      causaRaiz: '🔍 CAUSA RAIZ: Ter baixo risco é um grande ativo, mas pode ser mantido e otimizado ainda mais com estratégias preventivas adequadas. Pesquisas mostram que hábitos inadequados ao longo do tempo podem aumentar riscos metabólicos. Um distribuidor Herbalife pode criar estratégias preventivas personalizadas, recomendar produtos que mantêm saúde metabólica e fornecer orientações para manter seu bem-estar em longo prazo. A prevenção é sempre melhor que o tratamento.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Considere um acompanhamento preventivo com um distribuidor Herbalife para manter seu baixo risco. Um profissional pode criar estratégias personalizadas, recomendar produtos que mantêm saúde metabólica e fornecer orientações para manter sua excelente condição ao longo do tempo. A prevenção garante qualidade de vida contínua.',
      plano7Dias: '📅 PLANO 7 DIAS: Um distribuidor Herbalife pode criar um plano preventivo personalizado que inclui: otimização de saúde metabólica, estratégias para manter baixo risco, produtos preventivos que mantêm saúde, orientações sobre combinações ideais de alimentos e acompanhamento para garantir que você mantenha sua excelente condição. A prevenção é a melhor estratégia.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Com base no seu perfil, um distribuidor Herbalife pode recomendar produtos preventivos que mantêm sua saúde metabólica, como produtos de manutenção, suplementos preventivos, produtos para saúde cardiovascular e protocolos personalizados. A suplementação preventiva mantém sua excelente saúde.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um distribuidor Herbalife pode fornecer orientações sobre otimização nutricional preventiva, estratégias para manter excelente saúde metabólica, receitas que potencializam bem-estar, dicas sobre combinações alimentares ideais e suporte para criar hábitos que mantêm sua saúde metabólica em excelência. A prevenção garante qualidade de vida contínua.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Mantenha seu baixo risco com estratégias preventivas personalizadas. Entre em contato com um distribuidor Herbalife para receber orientações e produtos que mantêm seu bem-estar. A prevenção é o melhor investimento para sua saúde a longo prazo!'
    }
  }
}

