/**
 * DIAGNÓSTICOS: Diagnóstico de Sintomas Intestinais - ÁREA WELLNESS
 * 
 * Diagnósticos focados em identificar problemas intestinais
 * que estimulam contato com especialista em bem-estar
 */

import { DiagnosticosPorFerramenta } from '../types'

export const sintomasIntestinaisDiagnosticos: DiagnosticosPorFerramenta = {
  wellness: {
    problemasIntestinais: {
      diagnostico: '🌿 DIAGNÓSTICO: Seus sintomas indicam problemas intestinais que precisam de atenção. Um acompanhamento especializado é essencial para identificar causas e criar estratégias eficazes que melhorem significativamente sua saúde intestinal e qualidade de vida.',
      causaRaiz: '🔍 CAUSA RAIZ: Problemas intestinais podem ser causados por diversos fatores como desequilíbrios na microbiota, intolerâncias alimentares, estresse, falta de fibras, ou até mesmo problemas de digestão. Pesquisas mostram que até 60% das pessoas têm problemas digestivos não diagnosticados que impactam negativamente sua qualidade de vida, energia e bem-estar geral. Quando não identificados e tratados, esses problemas podem piorar ao longo do tempo. Um especialista em bem-estar experiente pode ajudar a identificar padrões alimentares problemáticos, criar um plano personalizado de saúde digestiva, recomendar produtos específicos para saúde intestinal (como probióticos, fibras e enzimas digestivas) e fornecer acompanhamento constante. A combinação de produtos adequados com estratégias nutricionais personalizadas faz toda diferença na saúde intestinal.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Busque um acompanhamento especializado com um especialista em bem-estar para identificar e tratar seus problemas intestinais. Um profissional experiente pode criar um plano personalizado que inclui produtos específicos para saúde intestinal, estratégias nutricionais otimizadas, protocolos de suplementação adequados e acompanhamento constante. Produtos de qualidade como probióticos, fibras e suplementos digestivos podem ser fundamentais para restaurar sua saúde intestinal de forma segura e eficaz.',
      plano7Dias: '📅 PLANO 7 DIAS: Conecte-se com um especialista em bem-estar para receber um plano personalizado que inclui: produtos específicos para saúde intestinal (probióticos, fibras, enzimas), estratégias nutricionais otimizadas para digestão, cronograma detalhado de uso dos produtos, acompanhamento diário para monitorar melhorias, ajustes conforme sua resposta individual e suporte constante. O suporte profissional é fundamental para uma recuperação segura e eficaz da saúde intestinal.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Um especialista em bem-estar pode recomendar produtos específicos que ajudam a melhorar a saúde intestinal, como probióticos para equilibrar microbiota, fibras para regular trânsito intestinal, enzimas digestivas para melhor absorção, produtos para reduzir inflamação intestinal e protocolos personalizados de suplementação. O acompanhamento profissional garante que você use os produtos certos nas doses adequadas, potencializando resultados e evitando excessos.',
      alimentacao: '🍎 ALIMENTAÇÃO: Com o acompanhamento de um especialista em bem-estar, você receberá orientações personalizadas sobre alimentação que melhora saúde intestinal, como alimentos ricos em fibras, estratégias de combinação de alimentos para melhor digestão, receitas práticas e deliciosas, alimentos probióticos naturais e suporte constante para criar hábitos alimentares que mantêm intestino saudável. O mentor te ajuda a entender como cada alimento impacta sua saúde intestinal.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Sua qualidade de vida pode melhorar significativamente ao tratar adequadamente seus problemas intestinais. Entre em contato com um especialista em bem-estar para receber um acompanhamento especializado que vai desde produtos específicos para saúde intestinal até estratégias personalizadas de nutrição. Você não precisa conviver com desconforto digestivo — um profissional pode te ajudar a encontrar soluções que transformam seu bem-estar. Sua jornada para saúde intestinal começa agora!'
    },
    problemasModerados: {
      diagnostico: '🌿 DIAGNÓSTICO: Você apresenta alguns sinais que podem indicar problemas intestinais moderados. Um acompanhamento pode ajudar a otimizar sua saúde digestiva e prevenir problemas futuros.',
      causaRaiz: '🔍 CAUSA RAIZ: Problemas intestinais moderados podem causar sintomas intermitentes que muitas vezes passam despercebidos ou são atribuídos a outras causas como cansaço ou má alimentação. Pesquisas indicam que muitas pessoas vivem com desequilíbrios digestivos sutis sem saber que são causados por padrões alimentares ou falta de nutrientes adequados. Um especialista em bem-estar pode ajudar a identificar esses padrões sutis, criar um plano de otimização digestiva e recomendar produtos que sejam adequados ao seu perfil, melhorando sua qualidade de vida e prevenindo que problemas se tornem mais severos.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Conecte-se com um especialista em bem-estar para uma avaliação personalizada que pode identificar padrões alimentares que causam desconforto. Um profissional pode criar estratégias práticas para otimizar sua digestão, recomendar produtos adequados ao seu perfil e acompanhar sua evolução. Com pequenos ajustes personalizados, você pode melhorar significativamente sua saúde intestinal.',
      plano7Dias: '📅 PLANO 7 DIAS: Um especialista em bem-estar pode criar um plano personalizado que inclui: identificação de padrões alimentares problemáticos, estratégias práticas para otimizar digestão, produtos adequados ao seu perfil, cronograma de observação e ajustes, acompanhamento para monitorar melhorias e suporte para criar hábitos sustentáveis. O acompanhamento regular ajuda a identificar conexões sutis entre alimentação e sintomas.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Com base no seu perfil, um especialista em bem-estar pode recomendar produtos específicos que otimizam sua saúde intestinal, como probióticos suaves, fibras de manutenção, enzimas digestivas leves e protocolos personalizados. O acompanhamento profissional garante escolhas seguras e eficazes.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um especialista em bem-estar pode fornecer orientações personalizadas sobre alimentação que otimiza saúde intestinal, estratégias para identificar alimentos problemáticos, receitas práticas que melhoram digestão, dicas para manter variedade nutricional e suporte para criar hábitos alimentares que promovem bem-estar contínuo. O acompanhamento ajuda a transformar conhecimento em ação prática.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Com um acompanhamento personalizado, você pode otimizar sua saúde intestinal e melhorar seu bem-estar. Entre em contato com um especialista em bem-estar para receber estratégias práticas e produtos adequados ao seu perfil. Pequenos ajustes podem fazer grande diferença na sua qualidade de vida!'
    },
    saudeIntestinalAdequada: {
      diagnostico: '🌿 DIAGNÓSTICO: Você parece ter uma boa saúde intestinal! Mesmo assim, um acompanhamento preventivo pode ajudar a manter esse equilíbrio e otimizar ainda mais seu bem-estar digestivo.',
      causaRaiz: '🔍 CAUSA RAIZ: Ter boa saúde intestinal é um grande ativo, mas mesmo pessoas com boa digestão podem se beneficiar de otimizações preventivas. Pesquisas mostram que hábitos alimentares inadequados ao longo do tempo podem levar ao desenvolvimento de problemas digestivos. Um especialista em bem-estar pode criar estratégias preventivas personalizadas, recomendar produtos que mantêm a saúde intestinal e fornecer orientações para manter seu bem-estar em longo prazo. A prevenção é sempre melhor que o tratamento.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Considere um acompanhamento preventivo com um especialista em bem-estar para otimizar sua saúde intestinal. Um profissional pode criar estratégias personalizadas, recomendar produtos que mantêm a saúde digestiva e fornecer orientações para manter sua excelente condição ao longo do tempo. A prevenção garante qualidade de vida contínua.',
      plano7Dias: '📅 PLANO 7 DIAS: Um especialista em bem-estar pode criar um plano preventivo personalizado que inclui: otimização de saúde intestinal, estratégias para manter equilíbrio digestivo, produtos preventivos que mantêm a saúde, orientações sobre combinações ideais de alimentos e acompanhamento para garantir que você mantenha sua excelente condição. A prevenção é a melhor estratégia.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Com base no seu perfil, um especialista em bem-estar pode recomendar produtos preventivos que mantêm sua saúde intestinal, como probióticos de manutenção, fibras preventivas, suplementos para saúde digestiva e protocolos personalizados. A suplementação preventiva mantém sua excelente saúde.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um especialista em bem-estar pode fornecer orientações sobre otimização nutricional preventiva, estratégias para manter excelente saúde intestinal, receitas que potencializam bem-estar digestivo, dicas sobre combinações alimentares ideais e suporte para criar hábitos que mantêm sua saúde intestinal em excelência. A prevenção garante qualidade de vida contínua.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Mantenha sua excelente saúde intestinal com estratégias preventivas personalizadas. Entre em contato com um especialista em bem-estar para receber orientações e produtos que mantêm seu bem-estar. A prevenção é o melhor investimento para sua saúde a longo prazo!'
    }
  }
}

