/**
 * DIAGNÓSTICOS: Qual é o seu Tipo de Fome - ÁREA WELLNESS
 * 
 * Diagnósticos focados em identificar tipo de fome (física vs emocional)
 * que estimulam contato com especialista em bem-estar
 */

import { DiagnosticosPorFerramenta } from '../types'

export const tipoFomeDiagnosticos: DiagnosticosPorFerramenta = {
  wellness: {
    fomeEmocional: {
      diagnostico: '🍽️ DIAGNÓSTICO: Seu perfil indica que você tem padrões de fome emocional que precisam de atenção. Um acompanhamento especializado é essencial para identificar e controlar esses padrões, melhorando significativamente sua relação com a comida e resultados.',
      causaRaiz: '🔍 CAUSA RAIZ: Fome emocional ocorre quando você come em resposta a sentimentos como estresse, ansiedade, tristeza ou tédio, em vez de fome física real. Pesquisas mostram que até 75% das pessoas comem por razões emocionais sem perceber, o que pode impactar negativamente resultados de emagrecimento e bem-estar. Quando não identificados e tratados, esses padrões podem sabotar seus objetivos. Um especialista em bem-estar experiente pode ajudar a identificar gatilhos emocionais, criar estratégias personalizadas de controle, recomendar produtos que ajudam no controle da fome e fornecer suporte emocional constante. A combinação de produtos adequados com estratégias de controle emocional faz toda diferença na sua relação com a comida.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Busque um acompanhamento especializado com um especialista em bem-estar para identificar e controlar sua fome emocional. Um profissional experiente pode criar um plano personalizado que inclui produtos que ajudam no controle da fome, estratégias para diferenciar fome física de emocional, técnicas de controle emocional e acompanhamento constante. Produtos de qualidade como shakes e suplementos que controlam fome podem ser fundamentais para sua jornada.',
      plano7Dias: '📅 PLANO 7 DIAS: Conecte-se com um especialista em bem-estar para receber um plano personalizado que inclui: produtos que ajudam no controle da fome, estratégias para identificar gatilhos emocionais, técnicas de controle emocional, cronograma detalhado de uso dos produtos, acompanhamento diário para monitorar progresso e ajustes conforme sua resposta individual. O suporte profissional é fundamental para uma transformação segura e eficaz.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Um especialista em bem-estar pode recomendar produtos específicos que ajudam a controlar a fome, como shakes que promovem saciedade, suplementos que reduzem fome emocional, produtos para controle de ansiedade, protocolos personalizados de suplementação e estratégias de timing alimentar. O acompanhamento profissional garante que você use os produtos certos nas doses adequadas, potencializando resultados e evitando excessos.',
      alimentacao: '🍎 ALIMENTAÇÃO: Com o acompanhamento de um especialista em bem-estar, você receberá orientações personalizadas sobre alimentação que controla fome emocional, como alimentos que promovem saciedade, estratégias de combinação de alimentos, receitas práticas e deliciosas, técnicas para diferenciar fome física de emocional e suporte constante para criar hábitos alimentares que melhoram sua relação com a comida. O mentor te ajuda a entender como cada alimento e situação impacta sua fome.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Sua relação com a comida pode melhorar significativamente ao tratar adequadamente sua fome emocional. Entre em contato com um especialista em bem-estar para receber um acompanhamento especializado que vai desde produtos específicos para controle de fome até estratégias personalizadas de controle emocional. Você não precisa conviver com padrões de fome emocional — um profissional pode te ajudar a encontrar soluções que transformam seu bem-estar. Sua jornada para controle de fome começa agora!'
    },
    fomeMista: {
      diagnostico: '🍽️ DIAGNÓSTICO: Você apresenta padrões mistos de fome. Um acompanhamento pode ajudar a otimizar seu controle alimentar e criar estratégias personalizadas para cada tipo de fome.',
      causaRaiz: '🔍 CAUSA RAIZ: Fome mista indica que você tem momentos de fome física real e momentos de fome emocional. Pesquisas indicam que muitas pessoas têm dificuldade em diferenciar entre os dois tipos, o que pode impactar resultados. Um especialista em bem-estar pode ajudar a identificar padrões específicos, criar estratégias diferenciadas para cada tipo de fome, recomendar produtos adequados ao seu perfil e fornecer orientações para otimizar seu controle alimentar. A diferenciação entre tipos de fome é fundamental para resultados eficazes.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Conecte-se com um especialista em bem-estar para uma avaliação personalizada que pode identificar seus padrões específicos de fome. Um profissional pode criar estratégias práticas para diferenciar fome física de emocional, recomendar produtos adequados ao seu perfil e acompanhar sua evolução. Com pequenos ajustes personalizados, você pode melhorar significativamente seu controle alimentar.',
      plano7Dias: '📅 PLANO 7 DIAS: Um especialista em bem-estar pode criar um plano personalizado que inclui: identificação de padrões de fome, estratégias práticas para diferenciar tipos de fome, produtos adequados ao seu perfil, cronograma de observação e ajustes, acompanhamento para monitorar melhorias e suporte para criar hábitos sustentáveis. O acompanhamento regular ajuda a identificar conexões sutis entre emoções e fome.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Com base no seu perfil, um especialista em bem-estar pode recomendar produtos específicos que otimizam seu controle de fome, como shakes que promovem saciedade, suplementos de manutenção, produtos para controle equilibrado e protocolos personalizados. O acompanhamento profissional garante escolhas seguras e eficazes.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um especialista em bem-estar pode fornecer orientações personalizadas sobre alimentação que otimiza controle de fome, estratégias para identificar padrões, receitas práticas que melhoram saciedade, dicas para manter variedade nutricional e suporte para criar hábitos alimentares que promovem bem-estar contínuo. O acompanhamento ajuda a transformar conhecimento em ação prática.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Com um acompanhamento personalizado, você pode otimizar seu controle de fome e melhorar seu bem-estar. Entre em contato com um especialista em bem-estar para receber estratégias práticas e produtos adequados ao seu perfil. Pequenos ajustes podem fazer grande diferença na sua qualidade de vida!'
    },
    fomeFisica: {
      diagnostico: '🍽️ DIAGNÓSTICO: Você parece ter bom controle da fome física! Mesmo assim, um acompanhamento preventivo pode ajudar a manter esse controle e otimizar ainda mais sua alimentação.',
      causaRaiz: '🔍 CAUSA RAIZ: Ter bom controle da fome física é um grande ativo, mas mesmo pessoas com bom controle podem se beneficiar de otimizações preventivas. Pesquisas mostram que hábitos alimentares inadequados ao longo do tempo podem levar ao desenvolvimento de padrões de fome emocional. Um especialista em bem-estar pode criar estratégias preventivas personalizadas, recomendar produtos que mantêm o controle de fome e fornecer orientações para manter seu bem-estar em longo prazo. A prevenção é sempre melhor que o tratamento.',
      acaoImediata: '⚡ AÇÃO IMEDIATA: Considere um acompanhamento preventivo com um especialista em bem-estar para otimizar seu controle de fome. Um profissional pode criar estratégias personalizadas, recomendar produtos que mantêm o controle e fornecer orientações para manter sua excelente condição ao longo do tempo. A prevenção garante qualidade de vida contínua.',
      plano7Dias: '📅 PLANO 7 DIAS: Um especialista em bem-estar pode criar um plano preventivo personalizado que inclui: otimização de controle de fome, estratégias para manter equilíbrio alimentar, produtos preventivos que mantêm o controle, orientações sobre combinações ideais de alimentos e acompanhamento para garantir que você mantenha sua excelente condição. A prevenção é a melhor estratégia.',
      suplementacao: '💊 SUPLEMENTAÇÃO: Com base no seu perfil, um especialista em bem-estar pode recomendar produtos preventivos que mantêm seu controle de fome, como shakes de manutenção, suplementos preventivos, produtos para controle equilibrado e protocolos personalizados. A suplementação preventiva mantém sua excelente saúde.',
      alimentacao: '🍎 ALIMENTAÇÃO: Um especialista em bem-estar pode fornecer orientações sobre otimização nutricional preventiva, estratégias para manter excelente controle de fome, receitas que potencializam bem-estar alimentar, dicas sobre combinações alimentares ideais e suporte para criar hábitos que mantêm sua relação saudável com comida em excelência. A prevenção garante qualidade de vida contínua.',
      proximoPasso: '🎯 PRÓXIMO PASSO: Mantenha seu excelente controle de fome com estratégias preventivas personalizadas. Entre em contato com um especialista em bem-estar para receber orientações e produtos que mantêm seu bem-estar. A prevenção é o melhor investimento para sua saúde a longo prazo!'
    }
  }
}

