-- ============================================
-- SEED: Treinos Wellness (35 treinos)
-- Baseado na Lousa 11 - Treinos de 1, 3 e 5 Minutos
-- ============================================

-- Limpar dados existentes (opcional - descomente se necessário)
-- TRUNCATE TABLE wellness_treinos CASCADE;

-- ============================================
-- TREINOS DE 1 MINUTO (15 treinos)
-- ============================================

INSERT INTO wellness_treinos (codigo, tipo, titulo, conceito, exemplo_pratico, acao_diaria, gatilho_noel, ordem) VALUES
('treino-1min-01', '1min', 'O Poder do Primeiro Passo', 'O primeiro passo é sempre o mais difícil, mas também o mais importante. Não precisa ser perfeito, só precisa ser dado.', 'Em vez de pensar em "preciso fazer 10 convites", pense "vou fazer 1 convite agora".', 'Faça 1 ação agora, mesmo que pequena. Pode ser 1 mensagem, 1 link enviado, 1 contato.', 'Quando distribuidor está procrastinando ou travado no início do dia', 1),
('treino-1min-02', '1min', 'O Simples Funciona', 'Sistemas complexos falham. O que funciona é o simples feito consistentemente.', 'Em vez de criar 10 estratégias diferentes, use 1 estratégia 10 vezes.', 'Escolha 1 script e use ele hoje. Não mude, só execute.', 'Quando distribuidor está complicando demais ou buscando soluções complexas', 2),
('treino-1min-03', '1min', 'Não Pare 2 Dias Seguidos', 'Consistência não é fazer todo dia. É não parar 2 dias seguidos.', 'Se você parou hoje, amanhã precisa voltar. Não deixe passar 2 dias.', 'Se você parou ontem, faça algo hoje. Mesmo que seja mínimo.', 'Quando distribuidor parou de agir ou está desanimado', 3),
('treino-1min-04', '1min', 'Você Não Precisa Saber Tudo', 'Você não precisa ser expert para começar. Você aprende fazendo.', 'Não espere saber tudo sobre produtos. Comece vendendo o que você já sabe.', 'Faça 1 ação hoje mesmo sem saber tudo. Você aprende no caminho.', 'Quando distribuidor está travado por falta de conhecimento', 4),
('treino-1min-05', '1min', 'Microvitórias Constroem o Macro', 'Grandes resultados são a soma de pequenas vitórias diárias.', '1 venda hoje + 1 venda amanhã = 2 vendas. Pequeno hoje, grande no mês.', 'Celebre cada pequena vitória. 1 mensagem enviada já é vitória.', 'Quando distribuidor está desanimado por não ver resultados grandes', 5),
('treino-1min-06', '1min', 'Movimento Gera Clareza', 'Ação gera clareza. Você não precisa ter tudo claro para começar.', 'Em vez de planejar por horas, aja por 10 minutos. A clareza vem na ação.', 'Faça 1 ação agora. A clareza do que fazer vem depois.', 'Quando distribuidor está muito tempo planejando sem agir', 6),
('treino-1min-07', '1min', 'Uma Conversa Muda Tudo', 'Uma única conversa pode mudar sua semana. Uma venda, um recruta, uma conexão.', 'A mensagem que você não enviou hoje poderia ser a venda de amanhã.', 'Envie 1 mensagem agora. Pode ser a que muda tudo.', 'Quando distribuidor está hesitando em enviar mensagens', 7),
('treino-1min-08', '1min', 'A Energia Vem da Ação', 'Você não precisa estar motivado para agir. A motivação vem depois da ação.', 'Em vez de esperar motivação, aja. A energia vem quando você começa.', 'Faça 1 ação agora, mesmo sem vontade. A energia vem depois.', 'Quando distribuidor está sem energia ou motivação', 8),
('treino-1min-09', '1min', 'Feito é Melhor que Perfeito', 'Perfeição paralisa. Ação gera resultados.', 'Um script "ok" enviado hoje é melhor que um script "perfeito" que nunca sai.', 'Envie algo hoje, mesmo que não esteja perfeito. Feito é melhor.', 'Quando distribuidor está travado buscando perfeição', 9),
('treino-1min-10', '1min', 'Você Nunca Começa do Zero', 'Cada ação que você fez antes conta. Você não está começando do zero.', 'Mesmo que tenha parado, você já tem experiência, contatos, conhecimento.', 'Lembre-se: você já tem algo. Use isso para começar hoje.', 'Quando distribuidor sente que está começando do zero', 10),
('treino-1min-11', '1min', 'Se Travou, Reduza', 'Se você travou, não force. Reduza a meta e continue.', 'Em vez de 10 convites, faça 2. Em vez de 5 follow-ups, faça 1.', 'Reduza sua meta de hoje pela metade. Continue, mas com menos pressão.', 'Quando distribuidor está travado por metas muito altas', 11),
('treino-1min-12', '1min', 'Confie no Sistema', 'O sistema funciona. Você só precisa executar consistentemente.', 'O 2-5-10 funciona. Os Links Wellness funcionam. Só execute.', 'Use o sistema hoje. Não invente, só execute o que já funciona.', 'Quando distribuidor está duvidando do sistema ou querendo inventar', 12),
('treino-1min-13', '1min', 'Seu Ritmo Cria Seu Resultado', 'Não importa o ritmo dos outros. Seu ritmo constante cria seus resultados.', '1 ação por dia por 30 dias é melhor que 30 ações em 1 dia e depois parar.', 'Mantenha seu ritmo hoje. Não precisa ser o mais rápido, só consistente.', 'Quando distribuidor está se comparando com outros', 13),
('treino-1min-14', '1min', 'Avance Mesmo Sem Vontade', 'Dias sem vontade são normais. Avance mesmo assim.', 'Você não precisa estar animado para agir. Ação gera animação.', 'Faça 1 ação hoje mesmo sem vontade. A vontade vem depois.', 'Quando distribuidor está sem vontade ou desanimado', 14),
('treino-1min-15', '1min', 'Você Está Criando Sua Própria Liberdade', 'Cada ação hoje é um passo em direção à sua liberdade financeira.', '1 venda hoje + 1 recruta esta semana = você está construindo seu futuro.', 'Lembre-se: cada ação hoje constrói sua liberdade. Continue.', 'Quando distribuidor precisa de motivação de longo prazo', 15);

-- ============================================
-- TREINOS DE 3 MINUTOS (10 treinos)
-- ============================================

INSERT INTO wellness_treinos (codigo, tipo, titulo, conceito, exemplo_pratico, acao_diaria, gatilho_noel, ordem) VALUES
('treino-3min-01', '3min', 'Como usar links para abrir conversas', 'Links Wellness são portas de entrada. Use para abrir conversas, não para fechar vendas.', 'Envie um link de curiosidade (ex: Calculadora de Água) e depois pergunte o resultado. Isso abre a conversa naturalmente.', 'Hoje, envie 1 link para alguém e depois pergunte o resultado. Use isso para abrir a conversa.', 'Quando distribuidor não sabe como iniciar conversas', 16),
('treino-3min-02', '3min', 'O método 2-5-10 explicado', '2 convites leves, 5 follow-ups, 10 interações. Isso é o mínimo diário que constrói seu negócio.', '2 convites = 2 links enviados. 5 follow-ups = 5 pessoas que você já abordou. 10 interações = 10 conversas sem intenção comercial.', 'Hoje, faça pelo menos: 2 convites, 5 follow-ups, 10 interações. Anote e complete.', 'Quando distribuidor não entende o método 2-5-10', 17),
('treino-3min-03', '3min', 'Como fazer follow-up sem parecer insistente', 'Follow-up é cuidado, não insistência. Mostre interesse genuíno, não apenas venda.', 'Em vez de "você comprou?", pergunte "como está indo com o produto que te mostrei?". Mostre interesse real.', 'Hoje, faça 1 follow-up genuíno. Pergunte como a pessoa está, não apenas sobre venda.', 'Quando distribuidor está com dificuldade em fazer follow-up', 18),
('treino-3min-04', '3min', 'Como interpretar resultados dos Links Wellness', 'Cada resultado de link mostra uma necessidade. Use isso para personalizar sua abordagem.', 'Se alguém preencheu "Calculadora de Água" e o resultado foi baixo, essa pessoa precisa de hidratação. Ofereça produtos relacionados.', 'Hoje, analise 1 resultado de link que você enviou. O que ele revela sobre a pessoa?', 'Quando distribuidor recebe resultados de links mas não sabe o que fazer', 19),
('treino-3min-05', '3min', 'Como vender sem vender (venda leve)', 'Venda leve é mostrar benefício, não pressionar compra. Conte histórias, mostre resultados, deixe a pessoa querer.', 'Em vez de "compre agora", diga "tenho uma cliente que usou e teve esse resultado. Quer conhecer?".', 'Hoje, faça 1 abordagem de venda leve. Mostre benefício, não pressione.', 'Quando distribuidor está sendo muito direto na venda', 20),
('treino-3min-06', '3min', 'Como identificar um lead quente', 'Lead quente faz perguntas, demonstra interesse, responde rápido. Identifique e priorize.', 'Se alguém pergunta preço, como funciona, ou demonstra interesse real, esse é um lead quente. Priorize esse contato.', 'Hoje, identifique 1 lead quente na sua lista. Priorize esse contato hoje.', 'Quando distribuidor tem muitos contatos mas não sabe priorizar', 21),
('treino-3min-07', '3min', 'Como fazer fechamento leve', 'Fechamento leve é oferecer, não pressionar. Dê opções, mostre facilidade, deixe a pessoa escolher.', 'Em vez de "você vai comprar?", diga "tenho 2 opções para você. Qual faz mais sentido?".', 'Hoje, pratique 1 fechamento leve. Ofereça opções, não pressione.', 'Quando distribuidor está com dificuldade em fechar vendas', 22),
('treino-3min-08', '3min', 'Como recrutar naturalmente', 'Recrutamento natural é mostrar oportunidade, não forçar entrada. Conte sua história, mostre possibilidades.', 'Em vez de "quer entrar no negócio?", diga "eu transformei meu consumo em renda. Quer saber como?".', 'Hoje, faça 1 abordagem de recrutamento natural. Conte sua história, não force.', 'Quando distribuidor quer recrutar mas não sabe como abordar', 23),
('treino-3min-09', '3min', 'Como duplicar usando o NOEL', 'NOEL pode ajudar sua equipe. Ensine seus recrutas a usarem o NOEL para vender e recrutar.', 'Mostre para seu recruta: "usa o NOEL assim para vender" e "usa o NOEL assim para recrutar". Duplique seu conhecimento.', 'Hoje, ensine 1 pessoa da sua equipe a usar o NOEL. Duplique seu conhecimento.', 'Quando distribuidor tem equipe mas não sabe como duplicar', 24),
('treino-3min-10', '3min', 'Como organizar sua semana de vendas', 'Semana organizada = resultados consistentes. Planeje dias para convites, follow-ups, fechamentos.', 'Segunda: planejar. Terça-Quinta: ação. Sexta: fechamentos. Sábado: revisão. Domingo: descanso.', 'Hoje, planeje sua semana: quais dias para convites, follow-ups, fechamentos?', 'Quando distribuidor está desorganizado ou sem planejamento', 25);

-- ============================================
-- TREINOS DE 5 MINUTOS (10 treinos)
-- ============================================

INSERT INTO wellness_treinos (codigo, tipo, titulo, conceito, exemplo_pratico, acao_diaria, gatilho_noel, ordem) VALUES
('treino-5min-01', '5min', 'O que realmente constrói um líder', 'Líder não é quem tem mais pessoas, é quem ajuda mais pessoas a terem resultados.', 'Em vez de focar em recrutar muitos, foque em ajudar poucos a terem resultados. Líderes são feitos ajudando, não recrutando.', 'Esta semana, foque em ajudar 1 pessoa da sua equipe a ter resultado. Isso te torna líder.', 'Quando distribuidor quer ser líder mas não sabe como', 26),
('treino-5min-02', '5min', 'Como construir uma equipe forte', 'Equipe forte é feita de pessoas comprometidas, não de muitas pessoas.', 'Melhor ter 3 pessoas comprometidas que 10 pessoas descomprometidas. Qualidade > quantidade.', 'Esta semana, identifique quem está realmente comprometido na sua equipe. Foque neles.', 'Quando distribuidor tem equipe mas não sabe como fortalecer', 27),
('treino-5min-03', '5min', 'Como ativar sua lista quente', 'Lista quente são pessoas que já demonstraram interesse. Ative com Links Wellness e follow-up.', 'Pessoas que já compraram, demonstraram interesse, ou são próximas = lista quente. Envie links e faça follow-up.', 'Hoje, identifique 5 pessoas da sua lista quente. Envie 1 link para cada e faça follow-up.', 'Quando distribuidor tem lista mas não sabe como ativar', 28),
('treino-5min-04', '5min', 'Como crescer com consistência e leveza', 'Crescimento consistente é melhor que crescimento rápido. Leveza é melhor que pressão.', '1 venda por semana por 1 ano = 52 vendas. Melhor que 10 vendas em 1 mês e depois parar.', 'Esta semana, foque em consistência. 1 ação por dia, sem pressão, sem estresse.', 'Quando distribuidor está pressionado ou estressado', 29),
('treino-5min-05', '5min', 'Como agir mesmo nos dias ruins', 'Dias ruins são normais. A diferença é que líderes agem mesmo nos dias ruins.', 'Mesmo sem vontade, faça 1 ação mínima. 1 mensagem, 1 link, 1 follow-up. Isso mantém o momentum.', 'Hoje, mesmo que esteja difícil, faça 1 ação mínima. Mantenha o momentum.', 'Quando distribuidor está tendo um dia ruim', 30),
('treino-5min-06', '5min', 'Como virar referência para sua equipe', 'Referência é quem tem resultados e ajuda outros a terem. Seja exemplo, não apenas chefe.', 'Em vez de mandar outros fazerem, faça você primeiro. Mostre resultados, depois ensine.', 'Esta semana, tenha 1 resultado pessoal (venda ou recruta) e depois ensine sua equipe a fazer igual.', 'Quando distribuidor quer ser referência mas não sabe como', 31),
('treino-5min-07', '5min', 'Como entender a filosofia YLADA', 'YLADA é sobre transformação através de bem-estar. Não é só vender, é transformar vidas.', 'Cada produto que você vende pode transformar uma vida. Cada recruta que você traz pode transformar uma família.', 'Hoje, lembre-se: você não está só vendendo, está transformando vidas. Isso dá propósito.', 'Quando distribuidor precisa de propósito ou significado', 32),
('treino-5min-08', '5min', 'Como trabalhar com metas semanais', 'Metas semanais são mais alcançáveis que mensais. Quebre grandes metas em pequenas semanas.', 'Em vez de "vou vender 10 este mês", pense "vou vender 2-3 esta semana". Mais alcançável.', 'Esta semana, defina 1 meta pequena e alcançável. Foque nela.', 'Quando distribuidor está com metas muito grandes ou desanimado', 33),
('treino-5min-09', '5min', 'Como usar a energia emocional ao seu favor', 'Emoções são energia. Use a energia positiva para vender, e transforme a negativa em ação.', 'Se está animado, use para vender. Se está desanimado, use para fazer follow-up (ação que não precisa de animação).', 'Hoje, identifique sua energia emocional. Use ela estrategicamente para suas ações.', 'Quando distribuidor está com emoções fortes (positivas ou negativas)', 34),
('treino-5min-10', '5min', 'Como criar um mês explosivo', 'Mês explosivo é feito de semanas consistentes. Não espere o mês, construa semana a semana.', 'Semana 1: base. Semana 2: aceleração. Semana 3: fechamentos. Semana 4: resultados. Construa semana a semana.', 'Esta semana, foque em construir a base. Próxima semana, acelere. Mês explosivo vem depois.', 'Quando distribuidor quer resultados rápidos ou está impaciente', 35);

-- Verificar inserção
SELECT COUNT(*) as total_treinos, tipo, COUNT(*) as por_tipo 
FROM wellness_treinos 
GROUP BY tipo 
ORDER BY tipo;
